define([], () => {
  return {
    "ApplyButtonLabel": "طبق",
    "ImportButtonLabel": "حمل",
    "ExportButtonLabel": "صدر",
    "FormatCodeButtonLabel": "كود التنسيق",
    "JsonFileRequiredMessage": "الرجاء تحميل ملف json",
    "EditPropertiesButtonLabel": "تحرير الخصائص",
    "EditPropertiesPanelHeaderText": "تحرير الخصائص الأولية",
    "SaveButtonLabel": "حفظ",
    "CancelButtonLabel": "إلغاء",
    "PeoplePickerSuggestedContacts": "الأشخاص المقترحون",
    "PeoplePickerSuggestedGroups": "المجموعات المقترحة",
    "PeoplePickerSuggestedCombined": "الأشخاص والمجموعات المقترحة",
    "PeoplePickerNoResults": "لم يتم العثور على نتائج",
    "PeoplePickerLoading": "جارٍ تحميل النتائج ...",
    "DatePickerMonthLongJanuary": "يناير",
    "DatePickerMonthShortJanuary": "يناير",
    "DatePickerMonthLongFebruary": "فبراير",
    "DatePickerMonthShortFebruary": "فبراير",
    "DatePickerMonthLongMarch": "مارس",
    "DatePickerMonthShortMarch": "مارس",
    "DatePickerMonthLongApril": "أبريل",
    "DatePickerMonthShortApril": "أبريل",
    "DatePickerMonthLongMay": "مايو",
    "DatePickerMonthShortMay": "مايو",
    "DatePickerMonthLongJune": "يونيه",
    "DatePickerMonthShortJune": "يونيه",
    "DatePickerMonthLongJuly": "يوليو",
    "DatePickerMonthShortJuly": "يوليو",
    "DatePickerMonthLongAugust": "أغسطس",
    "DatePickerMonthShortAugust": "أغسطس",
    "DatePickerMonthLongSeptember": "سبتمبر",
    "DatePickerMonthShortSeptember": "سبتمبر",
    "DatePickerMonthLongOctober": "أكتوبر",
    "DatePickerMonthShortOctober": "أكتوبر",
    "DatePickerMonthLongNovember": "نوفمبر",
    "DatePickerMonthShortNovember": "نوفمبر",
    "DatePickerMonthLongDecember": "ديسمبر",
    "DatePickerMonthShortDecember": "ديسمبر",
    "DatePickerDayLongSunday": "الأحد",
    "DatePickerDayShortSunday": "الأحد",
    "DatePickerDayLongMonday": "الأثنين",
    "DatePickerDayShortMonday": "الأثنين",
    "DatePickerDayLongTuesday": "الثلاثاء",
    "DatePickerDayShortTuesday": "الثلاثاء",
    "DatePickerDayLongWednesday": "الأربعاء",
    "DatePickerDayShortWednesday": "الأربعاء",
    "DatePickerDayLongThursday": "الخميس",
    "DatePickerDayShortThursday": "الخميس",
    "DatePickerDayLongFriday": "الجمعة",
    "DatePickerDayShortFriday": "الجمعة",
    "DatePickerDayLongSaturday": "السبت",
    "DatePickerDayShortSaturday": "السبت",
    "DatepickerGoToToday": "اليوم",
    "DateTimePickerDate": "تاريخ",
    "DateTimePickerTime": "الوقت",
    "ColorPickerButtonTitle": "اختر لون",
    "NotNumberValidationMessage": "يجب أن تكون القيمة رقمًا ، الفعلي هو:",
    "MinimumNumberValidationMessage": "يجب أن تكون القيمة أكبر من أو تساوي:",
    "MaximumNumberValidationMessage": "يجب أن تكون القيمة أقل من أو تساوي:",
    "TermPickerNoTerms": "مجموعة المصطلح لا تحتوي على أي شروط",
    "TermPickerExpandTitle": "توسيع مجموعة المصطلحات هذه",
    "TermPickerExpandNode": "توسيع هذه العقدة",
    "TermPickerMenuTermSet": "قائمة مجموعة المصطلحات",
    "TermPickerMenuTerm": "قائمة المدة",
    "TermPickerMenuGroup": "قائمة لمجموعة المصطلحات",
    "TermPickerInLabel": "في",
    "TermPickerTermSetLabel": "تعيين المدة",
    "propertyFieldMultiSelectNoOptions": "لا توجد خيارات للاختيار",
    "CollectionDataEmptyFields": "لم يتم توفير أي حقول لجمع البيانات.",
    "CollectionDataEmptyValue": "لا توجد بيانات في مجموعتك.",
    "CollectionAddRowButtonLabel": "إضافة البيانات إلى المجموعة",
    "CollectionDeleteRowButtonLabel": "حذف الصف الحالي",
    "CollectionSaveAndAddButtonLabel": "إضافة وحفظ",
    "CollectionDataItemShowErrorsLabel": "إظهار الأخطاء",
    "CollectionDataItemFieldRequiredLabel": "حقل مطلوب.",
    "CollectionDataItemFieldIssuesLabel": "القضايا الميدانية:",
    "InvalidUrlError": "عنوان URL المقدم غير صالح",
    "DescriptionLabel": "وصف",
    "MoreInfoLabel": "مزيد من المعلومات",
    "AboutGroupLabel": "حول",
    "SitePickerSearchBoxPlaceholder": "بحث...",
    "SitePickerNoResults": "لا نتائج للبحث",
    "SitePickerSitesChosen": "تم تحديد موقع (مواقع) الويب",
    "TeamPickerSearchBoxPlaceholder": "بحث...",
    "TeamPickerNoResults": "لا نتائج للبحث",
    "TeamPickerSitesChosen": "تم تحديد الفرق",
    "AddFileButtonLabel": "إضافة ملف",
    "AddImageButtonLabel": "إضافة صورة",
    "AriaCellValue": "{0} العمود ، {1}",
    "FilePickerCancelButtonLabel": "إلغاء",
    "CantValidateValidationMessage": "لم نتمكن من التحقق من هذا الرابط. يرجى التحقق من الرابط والمحاولة مرة أخرى.",
    "ChangeFileLinkLabel": "تغيير الملف",
    "ChangeImageLinkLabel": "تغيير الصورة",
    "ChooseFileLinkLabel": "اختر ملف",
    "ChooseImageLinkLabel": "اختر صورة",
    "CopyrightUrl": "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
    "CopyrightWarning": "أنت مسؤول عن احترام حقوق الآخرين ، بما في ذلك حقوق النشر.",
    "CreativeCommonsMessage": "يتم تمييز هذه النتائج بتراخيص المشاع الإبداعي. راجع التراخيص للتأكد من التزامك بها.",
    "DateFormat": "مم / يوم / سنة حه: مم أ",
    "DocumentLabelTemplate": "{0},مستند,معدل {1},تم التعديل بواسطة {2},خاص",
    "DocumentLibraries": "مكتبات المستندات",
    "EditedByNamePlate": "حررت بواسطة ",
    "EmptyFileSize": "0 بايت",
    "FilePickerHeader": "منتقي الملفات",
    "FileSizeField": "حجم الملف",
    "FolderAltText": "مجلد",
    "FolderBackPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    "FolderFrontPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    "FolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    "FolderLabelTemplate": "{0} ، مجلد ، معدل {1} ، تم التعديل بواسطة {2} ، {3} عنصر ، خاص",
    "FromLinkLinkLabel": "من رابط",
    "ImageAltText": ".{0} صورة",
    "ImageAriaLabelTemplate": ".{0} صورة",
    "ImageLayoutPlaceholderText": "تَخطِيط",
    "ImageSizePlaceholderText": "حجم الصورة",
    "ItemChildCountField": "عدد العناصر التابعة",
    "LayoutOptionAll": "الجميع",
    "LayoutOptionSquare": "مربع",
    "LayoutOptionTall": "طويل",
    "LayoutOptionWide": "واسع",
    "LearnMoreLink": "تعلم المزيد.",
    "LicenseOptionAll": "الجميع",
    "LicenseOptionAny": "المشاع الإبداعي فقط",
    "LicensePlaceholderText": "رخصة",
    "LinkFileInstructions": "لصق ارتباط إلى ملف في OneDrive for Business أو SharePoint Online",
    "ExternalLinkFileInstructions": "الصق ارتباطًا بموقع أو صفحة أو مستند أو قائمة أو مكتبة (https: // أو http: //)",
    "LinkHeader": "من ارتباط",
    "LinkImageInstructions": "لصق ارتباط بصورة في OneDrive for Business أو SharePoint Online",
    "ListLayoutAriaLabel": "عرض الخيارات. {0} {1}.",
    "ListLayoutCompact": "عرض مكثف",
    "ListLayoutCompactDescription": "عرض العناصر والتفاصيل في قائمة مضغوطة",
    "ListLayoutList": "عرض القائمة",
    "ListLayoutListDescrition": "عرض العناصر والتفاصيل في قائمة",
    "ListLayoutTile": "عرض التجانب",
    "ListLayoutTileDescription": "عرض العناصر بمعاينات البلاط",
    "ListOptionsAlt": "خيارات العرض. {0} محددة.",
    "ListOptionsTitle": "فتح قائمة خيارات العرض",
    "Loading": "جار التحميل...",
    "ModifiedByField": "تم التعديل بواسطة",
    "ModifiedField": "التاريخ عدل",
    "NameField": "اسم",
    "No": "رقم",
    "ProvidedValueIsInvalid": "القيمة المقدمة غير صالحة",
    "NoExternalLinksValidationMessage": "نحن ندعم فقط الارتباط بالملفات الموجودة في مؤسستك.",
    "NoImageValidationMessage": "هذا ليس رابطًا لنوع ملف ندعمه. يمكنك فقط الارتباط بصورة.",
    "NoRecentFiles": "لا توجد ملفات حديثة",
    "NoRecentFilesDescription": "حاول تحديد ملف من موقعك ، أو تحميل واحد من جهازك.",
    "NoResultsBadEnglish": "*** لم يتم العثور على نتيجة. حاول تغيير خيارات التصفية",
    "ODModifiedField": "المعدل",
    "ODPhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    "ODRowArialLabelTemplate": "{0} ، {1} ، تم التعديل {2} ، تم التعديل بواسطة {3} ، {4} ، {5}",
    "OneDriveConfirmDialogBody": "هذا العنصر من موقع OneDrive الخاص بك. تكون الملفات والمجلدات الموجودة في OneDrive خاصة ما لم تشاركها. هل قمت بمشاركة هذا الملف مع أعضاء موقعك حتى يتمكنوا من الوصول إليه؟",
    "OneDriveConfirmDialogTitle": "أتحقق وحسب...",
    "OneDriveEmptyFolderAlt": "مجلد فارغ",
    "OneDriveEmptyFolderDescription": "لإضافة ملفات ، انتقل إلى OneDrive الخاص بك. يمكنك أيضًا إضافة ملفات إلى هذا المجلد باستخدام تطبيق OneDrive لجهاز الكمبيوتر الخاص بك.",
    "OneDriveEmptyFolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    "OneDriveEmptyFolderTitle": "هذا المجلد فارغ",
    "OneDriveRootFolderName": "الملفات",
    "OpenButtonLabel": "فتح",
    "PhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    "OrgAssetsTabLabel": "الصور والملفات المقدمة من مؤسستك",
    "PoweredByBing": "بدعم من Bing",
    "RecentDocumentsHeader": "الوثائق الأخيرة",
    "RecentImagesHeader": "الصور الحديثة",
    "RecentLinkLabel": "مؤخرًا",
    "SearchBoxPlaceholder": "البحث في الويب",
    "SearchResultAlt": "نتيجة الصورة لـ {0}.",
    "SearchResultAriaLabel": "اضغط على زر الإدخال لفتح مصدر الصورة في علامة تبويب جديدة.",
    "Selected": "المحدد",
    "SharingField": "مشاركة",
    "SharingPrivate": "خاص",
    "SharingShared": "مشتركة",
    "SiteLinkLabel": "موقع",
    "SizeOptionAll": "الجميع",
    "SizeOptionExtraLarge": "كبير جدًا",
    "SizeOptionLarge": "كبير",
    "SizeOptionMedium": "متوسط",
    "SizeOptionSmall": "صغير",
    "SizeUnit": [
      "بايت",
      "كيلو بايت",
      "ميغا بايت",
      "غيغابايت",
      "تيرا بايت",
      "بيتابايت",
      "إكسابايت",
      "زيتابيت",
      "يوتابايت "
    ],
    "SorryWebSearch": "عذرًا ، لم يتم تنفيذ هذه الوظيفة في هذا النموذج ، لأنها تتطلب مفتاح Bing API.",
    "SortedAscending": "مرتبة من الألف إلى الياء",
    "SortedDescending": "مصنفة من ي إلى أ",
    "TypeAriaLabel": "عمليات العمود لنوع الملف ، اضغط للفرز حسب نوع الملف",
    "UploadFileHeader": "رفع ملف",
    "UploadImageHeader": "تحميل الصور",
    "UploadLinkLabel": "تحميل",
    "WebSearchLinkLabel": "البحث في الويب",
    "Yes": "نعم",
    "StockImagesLinkLabel": "مخزون الصور",
    "StockImagesHeader": "مخزون الصور",
    "DateTime": {
      "L_RelativeDateTime_AFewSecondsFuture": "في بضع ثوان",
      "L_RelativeDateTime_AFewSeconds": "قبل ثوان",
      "L_RelativeDateTime_AboutAMinuteFuture": "في غضون دقيقة",
      "L_RelativeDateTime_AboutAMinute": "منذ دقيقة واحدة",
      "L_RelativeDateTime_XMinutesFuture": "في {0} دقيقة || في {0} دقيقة",
      "L_RelativeDateTime_XMinutes": "{0} دقيقة مضت || {0} دقيقة مضت",
      "L_RelativeDateTime_XMinutesFutureIntervals": "1|| 2-",
      "L_RelativeDateTime_XMinutesIntervals": "1|| 2-",
      "L_RelativeDateTime_AboutAnHourFuture": "في غضون ساعة",
      "L_RelativeDateTime_AboutAnHour": "منذ ساعة تقريبا",
      "L_RelativeDateTime_Tomorrow": "الغد",
      "L_RelativeDateTime_Yesterday": "في الامس",
      "L_RelativeDateTime_TomorrowAndTime": "غدًا في {0}",
      "L_RelativeDateTime_YesterdayAndTime": "أمس في {0}",
      "L_RelativeDateTime_XHoursFuture": "خلال {0} ساعة || خلال {0} ساعة",
      "L_RelativeDateTime_XHours": "قبل {0} ساعة || قبل {0} ساعة",
      "L_RelativeDateTime_XHoursFutureIntervals": "1|| 2-",
      "L_RelativeDateTime_XHoursIntervals": "1|| 2-",
      "L_RelativeDateTime_DayAndTime": "{0} في {1}",
      "L_RelativeDateTime_XDaysFuture": "{0} يوم من الآن || {0} يوم من الآن",
      "L_RelativeDateTime_XDays": "{0} يوم مضى || {0} يوم مضى",
      "L_RelativeDateTime_XDaysFutureIntervals": "1|| 2-",
      "L_RelativeDateTime_XDaysIntervals": "1|| 2-",
      "L_RelativeDateTime_Today": "اليوم"
    },
    "NewFolderNamePlaceholder": "أدخل اسم المجلد الخاص بك",
    "FolderFilterBoxPlaceholder": "تصفية المجلدات حسب الاسم",
    "FolderExplorerLoading": "تحميل المجلدات ...",
    "FolderExplorerNoItems": "لا يحتوي هذا المجلد على أي مجلدات فرعية.",
    "IncorrectGuidValidationMessage": "الرجاء إدخال معرف صالح",
    "SelectedLabel": "المحدد",
    "SelectIcon": "تحديد الرمز",
    "CloseButton": "إغلاق",
    "MonacoEditorOpenButtonLabel": "فتح المحرر",
    "MonacoEditorCancelButtonLabel": "إلغاء",
    "MonacoEditorSaveButtonLabel": "حفظ",
    "MonacoEditorPanelTitle": "تحرير القالب",
    "ColorPickerStrings": {
      "rootAriaLabelFormat": "منتقي الألوان، {0} تحديده.",
      "hex": "الهيكس",
      "red": "أحمر",
      "green": "أخضر",
      "blue": "أزرق",
      "alpha": "الفا",
      "transparency": "شفافية",
      "alphaAriaLabel": "الفا",
      "transparencyAriaLabel": "شفافية",
      "hueAriaLabel": "هوي",
      "svAriaLabel": "التشبع والسطوع",
      "svAriaValueFormat": "التشبع {0} السطوع {1}",
      "svAriaDescription": "استخدم مفاتيح الأسهم لليسار واليمين لضبط التشبع. استخدم مفاتيح الأسهم لأعلى ولأسفل لضبط السطوع.",
      "hexError": "يجب أن يتراوح طول القيم السداسية العشرية بين 3 و 6 أحرف",
      "alphaError": "يجب أن يكون ألفا بين 0 و 100",
      "transparencyError": "يجب أن تكون الشفافية بين 0 و 100",
      "redError": "يجب أن يكون اللون الأحمر بين 0 و 255",
      "greenError": "يجب أن يكون اللون الأخضر بين 0 و 255",
      "blueError": "يجب أن يكون اللون الأزرق بين 0 و 255"
    }
  };
});