define([], () => {
  return {
    "ApplyButtonLabel": "Použít",
    "ImportButtonLabel": "Dovoz",
    "ExportButtonLabel": "Vývoz",
    "FormatCodeButtonLabel": "Formátuj kód",
    "JsonFileRequiredMessage": "Prosím nahraj json soubor",
    "EditPropertiesButtonLabel": "Upravit vlastnosti",
    "EditPropertiesPanelHeaderText": "Upravit nezpracované vlastnosti",
    "SaveButtonLabel": "Uložit",
    "CancelButtonLabel": "Zrušit",
    "PeoplePickerSuggestedContacts": "Navržení lidé",
    "PeoplePickerSuggestedGroups": "Navržené skupiny",
    "PeoplePickerSuggestedCombined": "Navržení lidé a skupiny",
    "PeoplePickerNoResults": "Nenalezeny žádné výsledky",
    "PeoplePickerLoading": "Načítám výsledky...",
    "DatePickerMonthLongJanuary": "Leden",
    "DatePickerMonthShortJanuary": "Led",
    "DatePickerMonthLongFebruary": "Únor",
    "DatePickerMonthShortFebruary": "Úno",
    "DatePickerMonthLongMarch": "Březen",
    "DatePickerMonthShortMarch": "Bře",
    "DatePickerMonthLongApril": "Duben",
    "DatePickerMonthShortApril": "Dub",
    "DatePickerMonthLongMay": "Květen",
    "DatePickerMonthShortMay": "Kvě",
    "DatePickerMonthLongJune": "Červen",
    "DatePickerMonthShortJune": "Čen",
    "DatePickerMonthLongJuly": "Červenec",
    "DatePickerMonthShortJuly": "Čec",
    "DatePickerMonthLongAugust": "Srpen",
    "DatePickerMonthShortAugust": "Srp",
    "DatePickerMonthLongSeptember": "Září",
    "DatePickerMonthShortSeptember": "Zář",
    "DatePickerMonthLongOctober": "Říjen",
    "DatePickerMonthShortOctober": "Říj",
    "DatePickerMonthLongNovember": "Listopad",
    "DatePickerMonthShortNovember": "Lis",
    "DatePickerMonthLongDecember": "Prosinec",
    "DatePickerMonthShortDecember": "Pro",
    "DatePickerDayLongSunday": "Neděle",
    "DatePickerDayShortSunday": "Neď",
    "DatePickerDayLongMonday": "Pondělí",
    "DatePickerDayShortMonday": "Pon",
    "DatePickerDayLongTuesday": "Úterý",
    "DatePickerDayShortTuesday": "Úte",
    "DatePickerDayLongWednesday": "Středa",
    "DatePickerDayShortWednesday": "Stř",
    "DatePickerDayLongThursday": "Čtvrtek",
    "DatePickerDayShortThursday": "Čtv",
    "DatePickerDayLongFriday": "Pátek",
    "DatePickerDayShortFriday": "Pát",
    "DatePickerDayLongSaturday": "Sobota",
    "DatePickerDayShortSaturday": "Sob",
    "DatepickerGoToToday": "Dnes",
    "DateTimePickerDate": "Datum",
    "DateTimePickerTime": "Čas",
    "ColorPickerButtonTitle": "Vyber barvu",
    "NotNumberValidationMessage": "Hodnota by měla být číslo, ale je to:",
    "MinimumNumberValidationMessage": "Hodnota by měla být větší nebo rovna:",
    "MaximumNumberValidationMessage": "Hodnota by měla být menší nebo rovna:",
    "TermPickerNoTerms": "Sada termínů neobsahuje žádné termíny",
    "TermPickerExpandTitle": "Rozbal tuto sadu termínů",
    "TermPickerExpandNode": "Rozbal tento uzel",
    "TermPickerMenuTermSet": "Menu pro sadu termínů",
    "TermPickerMenuTerm": "Menu termín",
    "TermPickerMenuGroup": "Menu for skupinu termínů",
    "TermPickerInLabel": "v",
    "TermPickerTermSetLabel": "Sada termínů",
    "propertyFieldMultiSelectNoOptions": "Žádné možnosti k výběru",
    "CollectionDataEmptyFields": "Pro sběr dat nebyla poskytnuta žádná pole.",
    "CollectionDataEmptyValue": "V kolekci nejsou žádná data.",
    "CollectionAddRowButtonLabel": "Přidej data do kolekce",
    "CollectionDeleteRowButtonLabel": "Smaž současný řádek",
    "CollectionSaveAndAddButtonLabel": "Přidat a uložit",
    "CollectionDataItemShowErrorsLabel": "Ukaž chyby řádků",
    "CollectionDataItemFieldRequiredLabel": "Pole je vyžadováno.",
    "CollectionDataItemFieldIssuesLabel": "Chyby polí:",
    "InvalidUrlError": "Poskytnuté Url není platné",
    "DescriptionLabel": "Popis",
    "MoreInfoLabel": "Více informací",
    "AboutGroupLabel": "O",
    "SitePickerSearchBoxPlaceholder": "Vyhledávám...",
    "SitePickerNoResults": "Žádné výsledy vyhledávání",
    "SitePickerSitesChosen": "Vybraná webová stránka/stránky",
    "TeamPickerSearchBoxPlaceholder": "Vyhledávám...",
    "TeamPickerNoResults": "Žádné výsledy vyhledávání",
    "TeamPickerSitesChosen": "Vybraný tým/týmy",
    "AddFileButtonLabel": "Přidej soubor",
    "AddImageButtonLabel": "Přidej obrázek",
    "AriaCellValue": "{0} sloupec, {1}",
    "FilePickerCancelButtonLabel": "Zrušit",
    "CantValidateValidationMessage": "Tento odkaz se nám nepodařilo ověřit. Zkontrolujte a zkuste znovu.",
    "ChangeFileLinkLabel": "Změnit soubor",
    "ChangeImageLinkLabel": "Změnit obrázek",
    "ChooseFileLinkLabel": "Zvolit soubor",
    "ChooseImageLinkLabel": "Zvolit obrázek",
    "CopyrightUrl": "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
    "CopyrightWarning": "Jste odpovědní za respektování práv ostatních včetně autorských práv.",
    "CreativeCommonsMessage": "Výsledky jsou označeny licencemi Creative Commons. Zkontrolujte licence abyste se ujistili, že vyhovujete.",
    "DateFormat": "MM/DD/RRRR hh:mm A",
    "DocumentLabelTemplate": "{0}, dokument, upraven {1}, upravil {2}, soukromé",
    "DocumentLibraries": "Knihovny dokumentů",
    "EditedByNamePlate": "editoval",
    "EmptyFileSize": "0 bajtů",
    "FilePickerHeader": "Výběr souborů",
    "FileSizeField": "Velikost souboru",
    "FolderAltText": "Složka",
    "FolderBackPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    "FolderFrontPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    "FolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    "FolderLabelTemplate": "{0}, složka, upravena {1}, upravil {2}, {3} položek, soukromé",
    "FromLinkLinkLabel": "Z odkazu",
    "ImageAltText": ".{0} Obrázek",
    "ImageAriaLabelTemplate": ".{0} Obrázek",
    "ImageLayoutPlaceholderText": "Rozložení",
    "ImageSizePlaceholderText": "Velikost souboru",
    "ItemChildCountField": "Počet podřízených položek",
    "LayoutOptionAll": "Vše",
    "LayoutOptionSquare": "Čtverec",
    "LayoutOptionTall": "Vysoký",
    "LayoutOptionWide": "Široký",
    "LearnMoreLink": "Zjistěte více.",
    "LicenseOptionAll": "Vše",
    "LicenseOptionAny": "Pouze Creative Commons",
    "LicensePlaceholderText": "Licence",
    "LinkFileInstructions": "Vložte odkaz na soubor uložený na OneDrive for Business nebo SharePoint Online",
    "ExternalLinkFileInstructions": "Vložte odkaz na web, stránku, dokument, seznam, knihovnu (https:// nebo http://)",
    "LinkHeader": "Z odkazu",
    "LinkImageInstructions": "Vložte odkaz na obrázek uložený na OneDrive for Business nebo SharePoint Online",
    "ListLayoutAriaLabel": "Zobraz možnosti. {0}  {1} .",
    "ListLayoutCompact": "Kompaktní zobrazení",
    "ListLayoutCompactDescription": "Zobraz položky a podrobnosti v kompaktním zobrazení",
    "ListLayoutList": "Zobrazení seznamu",
    "ListLayoutListDescrition": "Zobraz položky a podrobnosti v zobrazení seznamu",
    "ListLayoutTile": "Zobrazení dlaždic",
    "ListLayoutTileDescription": "Zobraz položky s dlaždicovými náhledy",
    "ListOptionsAlt": "Zobraz vlastnosti. {0}  vybráno .",
    "ListOptionsTitle": "Otevři menu s vlastnostmi zobrazení",
    "Loading": "Nahrávám...",
    "ModifiedByField": "Změněno kým",
    "ModifiedField": "Datum změny",
    "NameField": "Jméno",
    "No": "Ne",
    "ProvidedValueIsInvalid": "Poskytnutá hodnota je neplatná",
    "NoExternalLinksValidationMessage": "Podporujeme pouze odkazy na soubory z vaší organizace.",
    "NoImageValidationMessage": "Toto není odkaz na soubor, který je podporován. Je možno pouze odkazovat na obrázky.",
    "NoRecentFiles": "Žádné nedávné soubory",
    "NoRecentFilesDescription": "Zkus vybrat soubor z tvého webu, nebo nahraj nějaký z tvého zařízení.",
    "NoResultsBadEnglish": "***Nenalezen žádný výsledek. Zkus změnit možnosti filtru",
    "ODModifiedField": "Modifikováno",
    "ODPhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    "ODRowArialLabelTemplate": "{0}, {1}, upraveno {2}, upravil {3}, {4}, {5}",
    "OneDriveConfirmDialogBody": "Tato položka pochází z vašeho webu OneDrive. Soubory a složky ve službě OneDrive jsou soukromé, pokud je nesdílíte. Sdíleli jste tento soubor se členy webu, aby k němu měli přístup?",
    "OneDriveConfirmDialogTitle": "Právě kontroluji...",
    "OneDriveEmptyFolderAlt": "Prázdná složka",
    "OneDriveEmptyFolderDescription": "Chcete-li přidat soubory, přejděte do služby OneDrive. Soubory do této složky můžete přidat také pomocí aplikace OneDrive pro váš počítač.",
    "OneDriveEmptyFolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    "OneDriveEmptyFolderTitle": "Tato složka je prázdná",
    "OneDriveRootFolderName": "Soubory",
    "OpenButtonLabel": "Otevři",
    "PhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    "OrgAssetsTabLabel": "Obrázky a soubory poskytnuté tvou organizací",
    "PoweredByBing": "Používá Bing",
    "RecentDocumentsHeader": "Nedávné dokumenty",
    "RecentImagesHeader": "Nedávné obrázky",
    "RecentLinkLabel": "Nedávné",
    "SearchBoxPlaceholder": "Prohledávání webu",
    "SearchResultAlt": "Výsledek obrázků pro {0}.",
    "SearchResultAriaLabel": "Stisknutím klávesy enter otevřete zdroj obrázku na nové kartě.",
    "Selected": "zvoleno",
    "SharingField": "Sdílení",
    "SharingPrivate": "Soukromé",
    "SharingShared": "Sdílené",
    "SiteLinkLabel": "Web",
    "SizeOptionAll": "Vše",
    "SizeOptionExtraLarge": "Extra velké",
    "SizeOptionLarge": "Velké",
    "SizeOptionMedium": "Střední",
    "SizeOptionSmall": "Malé",
    "SizeUnit": [
      "bajtů",
      "KB",
      "MB",
      "GB",
      "TB",
      "PB",
      "EB",
      "ZB",
      "YB"
    ],
    "SorryWebSearch": "Je nám líto, ale tato funkce není v této ukázce implementována, protože by vyžadovala klíč API služby Bing.",
    "SortedAscending": "Seřazeno od A do Z",
    "SortedDescending": "Seřazeno od Z do A",
    "TypeAriaLabel": "Operace se sloupci pro typ souboru, Stiskněte pro třídění podle typu souboru",
    "UploadFileHeader": "Nahraj soubor",
    "UploadImageHeader": "Nahraj obrázek",
    "UploadLinkLabel": "Nahraj",
    "WebSearchLinkLabel": "Prohledání webu",
    "Yes": "Ano",
    "StockImagesLinkLabel": "Sklad obrázků",
    "StockImagesHeader": "Sklad obrázků",
    "DateTime": {
      "L_RelativeDateTime_AFewSecondsFuture": "Za několik sekund",
      "L_RelativeDateTime_AFewSeconds": "Před několika sekundami",
      "L_RelativeDateTime_AboutAMinuteFuture": "Asi za minutu",
      "L_RelativeDateTime_AboutAMinute": "Asi před minutou",
      "L_RelativeDateTime_XMinutesFuture": "Za {0} minut||Za {0} minut",
      "L_RelativeDateTime_XMinutes": "Před {0} minutami||Před {0} minutami",
      "L_RelativeDateTime_XMinutesFutureIntervals": "1|| 2-",
      "L_RelativeDateTime_XMinutesIntervals": "1|| 2-",
      "L_RelativeDateTime_AboutAnHourFuture": "Asi za hodinu",
      "L_RelativeDateTime_AboutAnHour": "Asi před hodinou",
      "L_RelativeDateTime_Tomorrow": "Zítra",
      "L_RelativeDateTime_Yesterday": "Včera",
      "L_RelativeDateTime_TomorrowAndTime": "Zítra v {0}",
      "L_RelativeDateTime_YesterdayAndTime": "Včera v {0}",
      "L_RelativeDateTime_XHoursFuture": "Za {0} hodin||Za {0} hodin",
      "L_RelativeDateTime_XHours": "Před {0} hodinami||Před {0} hodinami",
      "L_RelativeDateTime_XHoursFutureIntervals": "1|| 2-",
      "L_RelativeDateTime_XHoursIntervals": "1|| 2-",
      "L_RelativeDateTime_DayAndTime": "{0} v {1}",
      "L_RelativeDateTime_XDaysFuture": "Za {0} dnů od teď||Za {0} dnů od teď",
      "L_RelativeDateTime_XDays": "Před {0} dny||Před {0} dny",
      "L_RelativeDateTime_XDaysFutureIntervals": "1|| 2-",
      "L_RelativeDateTime_XDaysIntervals": "1|| 2-",
      "L_RelativeDateTime_Today": "Dnes"
    },
    "NewFolderNamePlaceholder": "Zadej název složky",
    "FolderFilterBoxPlaceholder": "Fitruj složky podle názvu",
    "FolderExplorerLoading": "Nahrávám složky...",
    "FolderExplorerNoItems": "Tato složka nemá žádné podsložky.",
    "IncorrectGuidValidationMessage": "Prosím zadejte platné GUID",
    "SelectedLabel": "Vybráno",
    "SelectIcon": "Vyber ikonu",
    "CloseButton": "Zavřít",
    "MonacoEditorOpenButtonLabel": "Otevři editor",
    "MonacoEditorCancelButtonLabel": "Zrušit",
    "MonacoEditorSaveButtonLabel": "Uložit",
    "MonacoEditorPanelTitle": "Edituj šablonu",
    "ColorPickerStrings": {
      "rootAriaLabelFormat": "Vybráno {0} výběr barvy.",
      "hex": "Šesté vydání",
      "red": "červený",
      "green": "zelený",
      "blue": "Vyplnit",
      "alpha": "Alfa",
      "transparency": "průhlednost",
      "alphaAriaLabel": "Alfa",
      "transparencyAriaLabel": "průhlednost",
      "hueAriaLabel": "Ljubov",
      "svAriaLabel": "Sytost a jas",
      "svAriaValueFormat": "Sytost {0} jas {1}",
      "svAriaDescription": "Pomocí kláves se šipkami doleva a doprava upravte sytost. Pomocí kláves se šipkami nahoru a dolů upravte jas.",
      "hexError": "Šestiúhelníkové hodnoty musí mít délku 3 až 6 znaků",
      "alphaError": "Alfa by měla být mezi 0 a 100",
      "transparencyError": "Průhlednost musí být mezi 0 a 100",
      "redError": "Červená by měla být mezi 0 a 255",
      "greenError": "Zelená by měla být mezi 0 a 255",
      "blueError": "Modrá by měla být mezi 0 a 255"
    }
  };
});