define([], function () {
  return {
    // PeoplePicker labels
    'PeoplePickerSuggestedContacts': 'Suggested people',
    'PeoplePickerSuggestedGroups': 'Suggested groups',
    'PeoplePickerSuggestedCombined': 'Suggested people and groups',
    'PeoplePickerNoResults': 'No result found',
    'PeoplePickerLoading': 'Loading results ...',

    //DatePicker labels
    'DatePickerMonthLongJanuary': 'January',
    'DatePickerMonthShortJanuary': 'Jan',
    'DatePickerMonthLongFebruary': 'February',
    'DatePickerMonthShortFebruary': 'Feb',
    'DatePickerMonthLongMarch': 'March',
    'DatePickerMonthShortMarch': 'Mar',
    'DatePickerMonthLongApril': 'April',
    'DatePickerMonthShortApril': 'Apr',
    'DatePickerMonthLongMay': 'May',
    'DatePickerMonthShortMay': 'May',
    'DatePickerMonthLongJune': 'June',
    'DatePickerMonthShortJune': 'Jun',
    'DatePickerMonthLongJuly': 'July',
    'DatePickerMonthShortJuly': 'Jul',
    'DatePickerMonthLongAugust': 'August',
    'DatePickerMonthShortAugust': 'Aug',
    'DatePickerMonthLongSeptember': 'September',
    'DatePickerMonthShortSeptember': 'Sept',
    'DatePickerMonthLongOctober': 'October',
    'DatePickerMonthShortOctober': 'Oct',
    'DatePickerMonthLongNovember': 'November',
    'DatePickerMonthShortNovember': 'Nov',
    'DatePickerMonthLongDecember': 'December',
    'DatePickerMonthShortDecember': 'Dec',
    'DatePickerDayLongSunday': 'Sunday',
    'DatePickerDayShortSunday': 'Sun',
    'DatePickerDayLongMonday': 'Monday',
    'DatePickerDayShortMonday': 'Mon',
    'DatePickerDayLongTuesday': 'Tuesday',
    'DatePickerDayShortTuesday': 'Tue',
    'DatePickerDayLongWednesday': 'Wednesday',
    'DatePickerDayShortWednesday': 'Web',
    'DatePickerDayLongThursday': 'Thursday',
    'DatePickerDayShortThursday': 'Thu',
    'DatePickerDayLongFriday': 'Friday',
    'DatePickerDayShortFriday': 'Fri',
    'DatePickerDayLongSaturday': 'Saturday',
    'DatePickerDayShortSaturday': 'Sat',

    'DatepickerGoToToday': 'Today',
    'DateTimePickerDate': 'Date',
    'DateTimePickerTime': 'Time'
  }
});
