define([], function() {
  return {
    ApplyButtonLabel: "Apply",
    ImportButtonLabel: "Import",
    ExportButtonLabel: "Export",
    JsonFileRequiredMessage: "Please upload a json file",
    SaveButtonLabel: "Sauvegarder",
    CancelButtonLabel: "Annuler",
    PeoplePickerSuggestedContacts: "Personnes suggérées",
    PeoplePickerSuggestedGroups: "Groupes suggérés",
    PeoplePickerSuggestedCombined: "Personnes et groupes suggérés",
    PeoplePickerNoResults: "Aucun résultat trouvé",
    PeoplePickerLoading: "Chargement des résultats ...",
    DatePickerMonthLongJanuary: "Janvier",
    DatePickerMonthShortJanuary: "Jan.",
    DatePickerMonthLongFebruary: "Février",
    DatePickerMonthShortFebruary: "Fev.",
    DatePickerMonthLongMarch: "Mars",
    DatePickerMonthShortMarch: "Mar.",
    DatePickerMonthLongApril: "Avril",
    DatePickerMonthShortApril: "Avr.",
    DatePickerMonthLongMay: "Mai",
    DatePickerMonthShortMay: "Mai",
    DatePickerMonthLongJune: "Juin",
    DatePickerMonthShortJune: "Juin",
    DatePickerMonthLongJuly: "Juillet",
    DatePickerMonthShortJuly: "Jul.",
    DatePickerMonthLongAugust: "Août",
    DatePickerMonthShortAugust: "Août",
    DatePickerMonthLongSeptember: "Septembre",
    DatePickerMonthShortSeptember: "Sept.",
    DatePickerMonthLongOctober: "Octobre",
    DatePickerMonthShortOctober: "Oct.",
    DatePickerMonthLongNovember: "Novembre",
    DatePickerMonthShortNovember: "Nov.",
    DatePickerMonthLongDecember: "Decembre",
    DatePickerMonthShortDecember: "Dec.",
    DatePickerDayLongSunday: "Dimanche",
    DatePickerDayShortSunday: "Dim",
    DatePickerDayLongMonday: "Lundi",
    DatePickerDayShortMonday: "Lun",
    DatePickerDayLongTuesday: "Mardi",
    DatePickerDayShortTuesday: "Mar",
    DatePickerDayLongWednesday: "Mercredi",
    DatePickerDayShortWednesday: "Mer",
    DatePickerDayLongThursday: "Jeudi",
    DatePickerDayShortThursday: "Jeu",
    DatePickerDayLongFriday: "Vendredi",
    DatePickerDayShortFriday: "Ven",
    DatePickerDayLongSaturday: "Samedi",
    DatePickerDayShortSaturday: "Sam",
    DatepickerGoToToday: "Aujourd\'hui",
    DateTimePickerDate: "Date",
    DateTimePickerTime: "Temps",
    ColorPickerButtonTitle: "Choisis une couleur",
    NotNumberValidationMessage: "La valeur doit être un nombre, la valeur actuel est :",
    MinimumNumberValidationMessage: "La valeur doit être supérieure à :",
    MaximumNumberValidationMessage: "La valeur doit être inférieure à :",
    TermPickerNoTerms: "L'ensemble de termes ne contient aucun terme",
    TermPickerExpandTitle: "Développer cet ensemble de termes",
    TermPickerExpandNode: "Développer ce nœud",
    TermPickerMenuTermSet: "Menu pour l'ensemble de termes",
    TermPickerMenuGroup: "Menu pour l'ensemble de termes",
    TermPickerInLabel: "dans",
    TermPickerTermSetLabel: "Ensemble de termes",
    propertyFieldMultiSelectNoOptions: "Aucune option à sélectionner",
    CollectionDataEmptyFields: "Aucun champ n'a été fourni pour la collection de données.",
    CollectionDataEmptyValue: "Aucune donnée dans votre collection.",
    CollectionAddRowButtonLabel: "Ajouter des données à la collection",
    CollectionDeleteRowButtonLabel: "Supprimer la ligne",
    CollectionSaveAndAddButtonLabel: "Ajouter et sauvegarder",
    CollectionDataItemShowErrorsLabel: "Afficher les erreurs de ligne",
    CollectionDataItemFieldRequiredLabel: "Champ obligatoire",
    InvalidUrlError: "L'URL fournie n'est pas valide",
    DescriptionLabel: "La description",
    MoreInfoLabel: "Plus d'informations",
    AboutGroupLabel: "Sur",

    AddFileButtonLabel: "Ajouter un fichier",
    AddImageButtonLabel: "Ajouter une image",
    AriaCellValue: "{0} colonne, {1}",
    FilePickerCancelButtonLabel: "Annuler",
    CantValidateValidationMessage: "Nous n'avons pas pu vérifier ce lien. S'il vous plaît vérifier le lien et essayer à nouveau.",
    ChangeFileLinkLabel: "Changer le fichier",
    ChangeImageLinkLabel: "Changer l'image",
    ChooseFileLinkLabel: "Choisir un fichier",
    ChooseImageLinkLabel: "Choisir une image",
    CopyrightUrl: "https://www.microsoft.com/fr-FR/legal/copyright/default.aspx",
    CopyrightWarning: "Vous êtes responsable du respect des droits d'autrui, y compris du droit d'auteur.",
    CreativeCommonsMessage: "Ces résultats sont étiquetés avec des licences Creative Commons. Passez en revue les licences pour vous assurer de votre conformité.",
    DateFormat: "DD/MM/YYYY hh:mm A",
    DocumentLabelTemplate: "{0}, Document, {1} modifié, édité par {2}, Privé",
    DocumentLibraries: "Bibliothèques de documents",
    EditedByNamePlate: "édité par ",
    EmptyFileSize: "0 octets",
    FilePickerHeader: "Sélecteur de fichiers",
    FileSizeField: "Taille du fichier",
    FolderAltText: "Dossier",
    FolderBackPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    FolderFrontPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    FolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    FolderLabelTemplate: "{0}, Dossier, Modifié le {1}, édité par {2}, {3} éléments, Privé",
    FromLinkLinkLabel: "À partir d'un lien",
    ImageAltText: ".{0} Image",
    ImageAriaLabelTemplate: ".{0} Image",
    ImageLayoutPlaceholderText: "Disposition",
    ImageSizePlaceholderText: "Taille de l'image",
    ItemChildCountField: "Nombre d'enfants",
    LayoutOptionAll: "Tous",
    LayoutOptionSquare: "Carré",
    LayoutOptionTall: "Grand",
    LayoutOptionWide: "Large",
    LearnMoreLink: "En savoir plus.",
    LicenseOptionAll: "Tous",
    LicenseOptionAny: "Creative Commons uniquement",
    LicensePlaceholderText: "Licence",
    LinkFileInstructions: "Coller un lien provenant de OneDrive Entreprise ou SharePoint Online",
    LinkHeader: "À partir d'un lien",
    LinkImageInstructions: "Coller le lien d'une image provenant de OneDrive Entreprise ou SharePoint Online",
    ListLayoutAriaLabel: "Afficher les options. {0} {1} .",
    ListLayoutCompact: "Vue compacte",
    ListLayoutCompactDescription: "Afficher les éléments et les détails dans une liste compacte",
    ListLayoutList: "Affichage en liste",
    ListLayoutListDescrition: "Afficher les éléments et les détails dans une liste",
    ListLayoutTile: "Affichage en mosaïque",
    ListLayoutTileDescription: "Afficher les éléments avec des aperçus en mosaïque",
    ListOptionsAlt: "Afficher les options. {0} sélectionnés .",
    ListOptionsTitle: "Ouvrez le menu des options d'affichage",
    Loading: "Chargement ...",
    ModifiedByField: "Modifié par",
    ModifiedField: "Date modifiée",
    NameField: "Nom",
    No: "non",
    ProvidedValueIsInvalid: "La valeur fournie est invalide",
    NoExternalLinksValidationMessage: "Nous prenons en charge uniquement les liens vers des fichiers de votre organisation (tenant).",
    NoImageValidationMessage: "Ce n'est pas un lien vers un type de fichier que nous prenons en charge. Vous pouvez uniquement créer un lien vers une image.",
    NoRecentFiles: "Aucun fichier récent",
    NoRecentFilesDescription: "Essayez de sélectionner un fichier sur votre site ou téléchargez-en un depuis votre appareil.",
    NoResultsBadEnglish: "*** Aucun résultat n'a été trouvé. Essayez de changer les options de filtre",
    ODModifiedField: "Modifié",
    ODPhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    ODRowArialLabelTemplate: "{0}, {1}, Modifié {2}, édité par {3}, {4}, {5}",
    OneDriveConfirmDialogBody: "Cet élément provient de votre OneDrive. Les fichiers et dossiers dans OneDrive sont privés, sauf si vous les partagez. Avez-vous partagé ce fichier avec les membres de votre site afin qu'ils puissent y accéder ?",
    OneDriveConfirmDialogTitle: "Nous vérifions ...",
    OneDriveEmptyFolderAlt: "Dossier vide",
    OneDriveEmptyFolderDescription: "Pour ajouter des fichiers, accédez à votre OneDrive. Vous pouvez également ajouter des fichiers à ce dossier à l'aide de l'application OneDrive de votre ordinateur.",
    OneDriveEmptyFolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    OneDriveEmptyFolderTitle: "Ce dossier est vide",
    OneDriveRootFolderName: "Fichiers",
    OpenButtonLabel: "Ouvrir",
    PhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    OrgAssetsTabLabel: "Images et fichiers fournis par votre organisation (tenant)",
    PoweredByBing: "Propulsé par Bing",
    RecentDocumentsHeader: "Documents récents",
    RecentImagesHeader: "Images récentes",
    RecentLinkLabel: "Récent",
    SearchBoxPlaceholder: "Recherche Internet",
    SearchResultAlt: "Résultat d'image pour {0}.",
    SearchResultAriaLabel: "Appuyez sur entrée pour ouvrir l'image dans un nouvel onglet.",
    Selected: "Sélectionné",
    SharingField: "Partage",
    SharingPrivate: "Privé",
    SharingShared: "Partagé",
    SiteLinkLabel: "Site",
    SizeOptionAll: "Tous",
    SizeOptionExtraLarge: "Extra Large",
    SizeOptionLarge: "Large",
    SizeOptionMedium: "Moyen",
    SizeOptionSmall: "Petit",
    SizeUnit: [
      "Octets",
      "Ko",
      "Mo",
      "Go",
      "To",
      "Po",
      "Eo",
      "Zo",
      "Yo"
    ],
    SorryWebSearch: "Désolé, cette fonction n'est pas implémentée dans cet exemple, car elle nécessiterait une clé d'API Bing.",
    SortedAscending: "Trié de A à Z",
    SortedDescending: "Tri de Z à A",
    TypeAriaLabel: "Opérations sur les colonnes \"Type de fichier\", sélectionné pour trier \"Type de fichier\"",
    UploadFileHeader: "Importer un fichier",
    UploadImageHeader: "Importer une image",
    UploadLinkLabel: "Importer",
    WebSearchLinkLabel: "Recherche Internet",
    Yes: "Oui",

    DateTime: {
      "L_RelativeDateTime_AFewSecondsFuture": "Dans quelques secondes",
      "L_RelativeDateTime_AFewSeconds": "Il y a quelques secondes",
      "L_RelativeDateTime_AboutAMinuteFuture": "Dans environ une minute",
      "L_RelativeDateTime_AboutAMinute": "Il y a environ une minute",
      "L_RelativeDateTime_XMinutesFuture": "Dans {0} minute||Dans {0} minutes",
      "L_RelativeDateTime_XMinutes": "Il y a {0} minute||Il y a {0} minutes",
      "L_RelativeDateTime_XMinutesFutureIntervals": "1||2-",
      "L_RelativeDateTime_XMinutesIntervals": "1||2-",
      "L_RelativeDateTime_AboutAnHourFuture": "Dans environ une heure",
      "L_RelativeDateTime_AboutAnHour": "Il y a environ une heure",
      "L_RelativeDateTime_Tomorrow": "Demain",
      "L_RelativeDateTime_Yesterday": "Hier",
      "L_RelativeDateTime_TomorrowAndTime": "Demain à {0}",
      "L_RelativeDateTime_YesterdayAndTime": "Hier à {0}",
      "L_RelativeDateTime_XHoursFuture": "Dans {0} heure||Dans {0} heures",
      "L_RelativeDateTime_XHours": "Il y a {0} heure||Il y a {0} heures",
      "L_RelativeDateTime_XHoursFutureIntervals": "1||2-",
      "L_RelativeDateTime_XHoursIntervals": "1||2-",
      "L_RelativeDateTime_DayAndTime": "{0} à {1}",
      "L_RelativeDateTime_XDaysFuture": "{0} jour à partir de maintenant || {0} jours à partir de maintenant",
      "L_RelativeDateTime_XDays": "Il y a {0} jour||Il y a {0} jours",
      "L_RelativeDateTime_XDaysFutureIntervals": "1||2-",
      "L_RelativeDateTime_XDaysIntervals": "1||2-",
      "L_RelativeDateTime_Today": "Aujourd'hui"
    },
  }
});