define([], function () {
  return {
    ApplyButtonLabel: "Bevestig",
    ImportButtonLabel: "Importeer",
    ExportButtonLabel: "Exporteer",
    JsonFileRequiredMessage: "Alleen JSON files toegestaan",
    SaveButtonLabel: "Opslaan",
    CancelButtonLabel: "Annuleren",
    PeoplePickerSuggestedContacts: "Voorgestelde personen",
    PeoplePickerSuggestedGroups: "Voorgestelde groepen",
    PeoplePickerSuggestedCombined: "Voorgestelde personen en groepen",
    PeoplePickerNoResults: "Geen resultaten gevonden",
    PeoplePickerLoading: "Resultaten laden ...",
    DatePickerMonthLongJanuary: "Januari",
    DatePickerMonthShortJanuary: "Jan",
    DatePickerMonthLongFebruary: "Februari",
    DatePickerMonthShortFebruary: "Feb",
    DatePickerMonthLongMarch: "Maart",
    DatePickerMonthShortMarch: "Maa",
    DatePickerMonthLongApril: "April",
    DatePickerMonthShortApril: "Apr",
    DatePickerMonthLongMay: "Mei",
    DatePickerMonthShortMay: "Mei",
    DatePickerMonthLongJune: "Juni",
    DatePickerMonthShortJune: "Jun",
    DatePickerMonthLongJuly: "Juli",
    DatePickerMonthShortJuly: "Jul",
    DatePickerMonthLongAugust: "Augustus",
    DatePickerMonthShortAugust: "Aug",
    DatePickerMonthLongSeptember: "September",
    DatePickerMonthShortSeptember: "Sept",
    DatePickerMonthLongOctober: "Oktober",
    DatePickerMonthShortOctober: "Okt",
    DatePickerMonthLongNovember: "November",
    DatePickerMonthShortNovember: "Nov",
    DatePickerMonthLongDecember: "December",
    DatePickerMonthShortDecember: "Dec",
    DatePickerDayLongSunday: "Zondag",
    DatePickerDayShortSunday: "Zon",
    DatePickerDayLongMonday: "Maandag",
    DatePickerDayShortMonday: "Maa",
    DatePickerDayLongTuesday: "Dinsdag",
    DatePickerDayShortTuesday: "Din",
    DatePickerDayLongWednesday: "Woensdag",
    DatePickerDayShortWednesday: "Woe",
    DatePickerDayLongThursday: "Donderdag",
    DatePickerDayShortThursday: "Don",
    DatePickerDayLongFriday: "Vrijdag",
    DatePickerDayShortFriday: "Vri",
    DatePickerDayLongSaturday: "Zaterdag",
    DatePickerDayShortSaturday: "Zat",
    DatepickerGoToToday: "Vandaag",
    DateTimePickerDate: "Dag",
    DateTimePickerTime: "Tijd",
    ColorPickerButtonTitle: "Kies een kleur",
    NotNumberValidationMessage: "De waarde moet een nummer zijn. Huidige waarde is:",
    MinimumNumberValidationMessage: "De waarde moet groter zijn dan of gelijk zijn aan:",
    MaximumNumberValidationMessage: "De waarde moet kleiner zijn dan of gelijk zijn aan:",
    TermPickerNoTerms: "De termen set heeft geen termen beschikbaar",
    TermPickerExpandTitle: "Vouw deze termen set uit",
    TermPickerExpandNode: "Vouw deze node uit",
    TermPickerMenuTermSet: "Menu voor de termen set",
    TermPickerMenuGroup: "Menu voor de groep",
    TermPickerInLabel: "in",
    TermPickerTermSetLabel: "Termen set",
    propertyFieldMultiSelectNoOptions: "Geen opties om te selecteren",
    CollectionDataEmptyFields: "Er zijn geen velden opgegeven voor de data collectie control.",
    CollectionDataEmptyValue: "Er is geen data in de collectie.",
    CollectionAddRowButtonLabel: "Voeg data toe aan de collectie",
    CollectionDeleteRowButtonLabel: "Verwijder de huidige rij",
    CollectionSaveAndAddButtonLabel: "Voeg toe en sla op",
    CollectionDataItemShowErrorsLabel: "Problemen tonen",
    CollectionDataItemFieldRequiredLabel: "Veld is verplicht.",
    InvalidUrlError: "De huidige URL is niet geldig",
    DescriptionLabel: "Beschrijving",
    MoreInfoLabel: "Meer info",
    AboutGroupLabel: "Over",

    AddFileButtonLabel: "Bestand toevoegen",
    AddImageButtonLabel: "Afbeelding toevoegen",
    AriaCellValue: "{0} kolom {1}",
    FilePickerCancelButtonLabel: "Annuleren",
    CantValidateValidationMessage: "We konden deze link niet verifiëren. Controleer de link en probeer het opnieuw.",
    ChangeFileLinkLabel: "Bestand wijzigen",
    ChangeImageLinkLabel: "Afbeelding wijzigen",
    ChooseFileLinkLabel: "Kies bestand",
    ChooseImageLinkLabel: "Afbeelding kiezen",
    CopyrightUrl: "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
    CopyrightWarning: "U bent verantwoordelijk voor het respecteren van de rechten van anderen, waaronder het auteursrecht.",
    CreativeCommonsMessage: "Deze resultaten zijn gelabeld met Creative Commons-licenties. Controleer de licenties om ervoor te zorgen dat u voldoet.",
    DateFormat: "MM/DD/JJJJ uu: mm A",
    DocumentLabelTemplate: "{0}, document, gewijzigd {1}, bewerkt door {2}, privé",
    DocumentLibraries: "Document bibliotheken",
    EditedByNamePlate: "bewerkt door ",
    EmptyFileSize: "0 bytes",
    FilePickerHeader: "Bestandskiezer",
    FileSizeField: "Bestandsgrootte",
    FolderAltText: "Map",
    FolderBackPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    FolderFrontPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    FolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    FolderLabelTemplate: "{0}, map, gewijzigd {1}, bewerkt door {2}, {3} items, privé",
    FromLinkLinkLabel: "Via een koppeling",
    ImageAltText: ". {0} afbeelding",
    ImageAriaLabelTemplate: ". {0} afbeelding",
    ImageLayoutPlaceholderText: "Indeling",
    ImageSizePlaceholderText: "Afbeeldingsgrootte",
    ItemChildCountField: "Aantal kinderen van artikel",
    LayoutOptionAll: "Alle",
    LayoutOptionSquare: "Square",
    LayoutOptionTall: "Lang",
    LayoutOptionWide: "Breed",
    LearnMoreLink: "Meer informatie.",
    LicenseOptionAll: "Alle",
    LicenseOptionAny: "Alleen Creative Commons",
    LicensePlaceholderText: "Licentie",
    LinkFileInstructions: "Een koppeling naar een bestand in OneDrive voor bedrijven of SharePoint Online plakken",
    LinkHeader: "Via een koppeling",
    LinkImageInstructions: "Een koppeling naar een afbeelding in OneDrive voor bedrijven of SharePoint Online plakken",
    ListLayoutAriaLabel: "Bekijk opties. {0} {1}.",
    ListLayoutCompact: "Compacte weergave",
    ListLayoutCompactDescription: "Items en Details in een compacte lijst weergeven",
    ListLayoutList: "Lijstweergave",
    ListLayoutListDescrition: "Items en Details in een lijst weergeven",
    ListLayoutTile: "Tegelweergave",
    ListLayoutTileDescription: "Items met tegel voorbeelden weergeven",
    ListOptionsAlt: "Bekijk opties. {0} geselecteerd.",
    ListOptionsTitle: "Het menu Weergaveopties openen",
    Loading: "Laden...",
    ModifiedByField: "Gewijzigd door",
    ModifiedField: "Wijzigingsdatum",
    NameField: "Naam",
    No: "No",
    ProvidedValueIsInvalid: "De opgegeven waarde is ongeldig",
    NoExternalLinksValidationMessage: "We ondersteunen alleen het linken naar bestanden in uw eigen organisatie.",
    NoImageValidationMessage: "Dit is geen koppeling naar een bestandstype dat we ondersteunen. U alleen een koppeling maken naar een afbeelding.",
    NoRecentFiles: "Geen recente bestanden",
    NoRecentFilesDescription: "Probeer een bestand van je site te selecteren of upload het van je apparaat.",
    NoResultsBadEnglish: "Er is geen resultaat gevonden. Probeer de filteropties te wijzigen",
    ODModifiedField: "Bewerkt",
    ODPhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    ODRowArialLabelTemplate: "{0}, {1}, gewijzigd {2}, bewerkt door {3}, {4}, {5}",
    OneDriveConfirmDialogBody: "Dit object is afkomstig van je OneDrive-site. Bestanden en mappen in OneDrive zijn privé tenzij je ze deelt. Heeft u dit bestand gedeeld met uw siteleden zodat ze het kunnen Cess?",
    OneDriveConfirmDialogTitle: "Gewoon controleren...",
    OneDriveEmptyFolderAlt: "Lege map",
    OneDriveEmptyFolderDescription: "Als u bestanden wilt toevoegen, gaat u naar OneDrive. U ook bestanden toevoegen aan deze map met behulp van de OneDrive-app voor uw computer.",
    OneDriveEmptyFolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    OneDriveEmptyFolderTitle: "Deze map is leeg",
    OneDriveRootFolderName: "Bestanden",
    OpenButtonLabel: "Open",
    PhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    OrgAssetsTabLabel: "Afbeeldingen en bestanden die door uw organisatie worden geleverd",
    PoweredByBing: "Mogelijk gemaakt door Bing",
    RecentDocumentsHeader: "Recente documenten",
    RecentImagesHeader: "Recente afbeeldingen",
    RecentLinkLabel: "Recente",
    SearchBoxPlaceholder: "Zoeken op het web",
    SearchResultAlt: "Beeld resultaat voor {0}.",
    SearchResultAriaLabel: "Druk op ENTER om de afbeeldingsbron in een nieuw tabblad te openen.",
    Selected: "Geselecteerde",
    SharingField: "Delen",
    SharingPrivate: "Privé",
    SharingShared: "Gedeelde",
    SiteLinkLabel: "Site",
    SizeOptionAll: "Alle",
    SizeOptionExtraLarge: "Extra grote",
    SizeOptionLarge: "Grote",
    SizeOptionMedium: "Medium",
    SizeOptionSmall: "Kleine",
    SizeUnit: [
      "Bytes",
      "Kb",
      "Mb",
      "Gb",
      "Tb",
      "PB",
      "Eb",
      "BV",
      "Yb"
    ],
    SorryWebSearch: "Sorry, deze functie is niet geïmplementeerd in dit voorbeeld, omdat er een Bing API-sleutel vereist.",
    SortedAscending: "Gesorteerd op A tot Z",
    SortedDescending: "Gesorteerd Z naar A",
    TypeAriaLabel: "Kolom bewerkingen voor bestandstype, druk op om te sorteren op bestandstype",
    UploadFileHeader: "Bestand uploaden",
    UploadImageHeader: "Afbeelding uploaden",
    UploadLinkLabel: "Uploaden",
    WebSearchLinkLabel: "Zoeken op het web",
    Yes: "Ja",

    DateTime: {
      "L_RelativeDateTime_AFewSecondsFuture": "Over een paar seconden",
      "L_RelativeDateTime_AFewSeconds": "Een paar seconden geleden",
      "L_RelativeDateTime_AboutAMinuteFuture": "Over ongeveer een minuut",
      "L_RelativeDateTime_AboutAMinute": "Ongeveer een minuut geleden",
      "L_RelativeDateTime_XMinutesFuture": "In {0} minuut||In {0} minuten",
      "L_RelativeDateTime_XMinutes": "{0} minuut geleden||{0} minuten geleden",
      "L_RelativeDateTime_XMinutesFutureIntervals": "1||2-",
      "L_RelativeDateTime_XMinutesIntervals": "1||2-",
      "L_RelativeDateTime_AboutAnHourFuture": "In ongeveer een uur",
      "L_RelativeDateTime_AboutAnHour": "Ongeveer een uur geleden",
      "L_RelativeDateTime_Tomorrow": "Morgen",
      "L_RelativeDateTime_Yesterday": "Gisteren",
      "L_RelativeDateTime_TomorrowAndTime": "Morgen om {0}",
      "L_RelativeDateTime_YesterdayAndTime": "Gisteren om {0}",
      "L_RelativeDateTime_XHoursFuture": "In {0} uur||In {0} uur",
      "L_RelativeDateTime_XHours": "{0} uur geleden||{0} uur geleden",
      "L_RelativeDateTime_XHoursFutureIntervals": "1||2-",
      "L_RelativeDateTime_XHoursIntervals": "1||2-",
      "L_RelativeDateTime_DayAndTime": "{0} om {1}",
      "L_RelativeDateTime_XDaysFuture": "{0} dag vanaf nu||{0} dagen vanaf nu",
      "L_RelativeDateTime_XDays": "{0} dag geleden||{0} dagen geleden",
      "L_RelativeDateTime_XDaysFutureIntervals": "1||2-",
      "L_RelativeDateTime_XDaysIntervals": "1||2-",
      "L_RelativeDateTime_Today": "Vandaag"
    },
  }
});
