define([], () => {
  return {
    "ApplyButtonLabel": "Anvende",
    "ImportButtonLabel": "Importere",
    "ExportButtonLabel": "Eksportere",
    "FormatCodeButtonLabel": "Formater kode",
    "JsonFileRequiredMessage": "Vennligst last opp en json fil",
    "EditPropertiesButtonLabel": "Rediger egenskaper",
    "EditPropertiesPanelHeaderText": "Rediger råegenskaper",
    "SaveButtonLabel": "Lagre",
    "CancelButtonLabel": "Avbryt",
    "PeoplePickerSuggestedContacts": "Foreslåtte personer",
    "PeoplePickerSuggestedGroups": "Foreslåtte grupper",
    "PeoplePickerSuggestedCombined": "Foreslåtte personer og grupper",
    "PeoplePickerNoResults": "Ingen result funnet",
    "PeoplePickerLoading": "Laster resultater ...",
    "DatePickerMonthLongJanuary": "Januar",
    "DatePickerMonthShortJanuary": "Jan",
    "DatePickerMonthLongFebruary": "Februar",
    "DatePickerMonthShortFebruary": "Februar",
    "DatePickerMonthLongMarch": "Mars",
    "DatePickerMonthShortMarch": "Skjemme",
    "DatePickerMonthLongApril": "April",
    "DatePickerMonthShortApril": "April",
    "DatePickerMonthLongMay": "Mai",
    "DatePickerMonthShortMay": "Mai",
    "DatePickerMonthLongJune": "Juni",
    "DatePickerMonthShortJune": "Juni",
    "DatePickerMonthLongJuly": "Juli",
    "DatePickerMonthShortJuly": "Juli",
    "DatePickerMonthLongAugust": "August",
    "DatePickerMonthShortAugust": "August",
    "DatePickerMonthLongSeptember": "September",
    "DatePickerMonthShortSeptember": "Sep",
    "DatePickerMonthLongOctober": "Oktober",
    "DatePickerMonthShortOctober": "Okt",
    "DatePickerMonthLongNovember": "November",
    "DatePickerMonthShortNovember": "November",
    "DatePickerMonthLongDecember": "Desember",
    "DatePickerMonthShortDecember": "Des",
    "DatePickerDayLongSunday": "Søndag",
    "DatePickerDayShortSunday": "Søn",
    "DatePickerDayLongMonday": "Mandag",
    "DatePickerDayShortMonday": "Man",
    "DatePickerDayLongTuesday": "Tirsdag",
    "DatePickerDayShortTuesday": "Tir",
    "DatePickerDayLongWednesday": "Onsdag",
    "DatePickerDayShortWednesday": "Ons",
    "DatePickerDayLongThursday": "Torsdag",
    "DatePickerDayShortThursday": "Tor",
    "DatePickerDayLongFriday": "Fredag",
    "DatePickerDayShortFriday": "Fre",
    "DatePickerDayLongSaturday": "Lørdag",
    "DatePickerDayShortSaturday": "Lør",
    "DatepickerGoToToday": "I dag",
    "DateTimePickerDate": "Dato",
    "DateTimePickerTime": "Tid",
    "ColorPickerButtonTitle": "Velg en farge",
    "NotNumberValidationMessage": "Verdien skal være et nummer, men er:",
    "MinimumNumberValidationMessage": "Verdien skal være større enn:",
    "MaximumNumberValidationMessage": "Verdien skal være mindre enn:",
    "TermPickerNoTerms": "Term settet inneholder ingen termer",
    "TermPickerExpandTitle": "Utvid dette termsettet",
    "TermPickerExpandNode": "Ekspander denne noden",
    "TermPickerMenuTermSet": "Meny for Termsettet",
    "TermPickerMenuTerm": "Meny for term",
    "TermPickerMenuGroup": "Meny for Termsettet",
    "TermPickerInLabel": "inn",
    "TermPickerTermSetLabel": "Termset",
    "propertyFieldMultiSelectNoOptions": "Ingen alternativer å velge",
    "CollectionDataEmptyFields": "Ingen felt ble angitt for samlingen av data.",
    "CollectionDataEmptyValue": "Ingen data i samlingen din.",
    "CollectionAddRowButtonLabel": "Legg data i samlingen",
    "CollectionDeleteRowButtonLabel": "Slett den gjeldene raden",
    "CollectionSaveAndAddButtonLabel": "Legg til og lagre",
    "CollectionDataItemShowErrorsLabel": "Vis radfeil",
    "CollectionDataItemFieldRequiredLabel": "Feltet er påkrevet.",
    "CollectionDataItemFieldIssuesLabel": "Feltproblemer:",
    "InvalidUrlError": "Den angitte nettadressen er ikke gyldig",
    "DescriptionLabel": "Beskrivelse",
    "MoreInfoLabel": "Mer informasjon",
    "AboutGroupLabel": "Om",
    "SitePickerSearchBoxPlaceholder": "Søke...",
    "SitePickerNoResults": "Ingen søkeresultater",
    "SitePickerSitesChosen": "Nettsted(er) valgt",
    "TeamPickerSearchBoxPlaceholder": "Søke...",
    "TeamPickerNoResults": "Ingen søkeresultater",
    "TeamPickerSitesChosen": "Valgt(e) lag(er)",
    "AddFileButtonLabel": "Legg til fil",
    "AddImageButtonLabel": "Legg til bilde",
    "AriaCellValue": "{0} kolonne, {1}",
    "FilePickerCancelButtonLabel": "Annullere",
    "CantValidateValidationMessage": "Vi kan ikke bekrefte denne koblingen. Kontroller koblingen, og prøv på nytt.",
    "ChangeFileLinkLabel": "Endre fil",
    "ChangeImageLinkLabel": "Endre bilde",
    "ChooseFileLinkLabel": "Velg fil",
    "ChooseImageLinkLabel": "Velg bilde",
    "CopyrightUrl": "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
    "CopyrightWarning": "Du er ansvarlig for å respektere andres rettigheter, inkludert opphavsrett.",
    "CreativeCommonsMessage": "Disse resultatene er merket med Creative Commons-lisenser. Se gjennom lisensene for å sikre at du overholder dem.",
    "DateFormat": "MM/DD/ÅÅÅÅ hh:mm A",
    "DocumentLabelTemplate": "{0}, Dokument, Endret {1}, redigert av {2}, Privat",
    "DocumentLibraries": "Dokumentbiblioteker",
    "EditedByNamePlate": "redigert av ",
    "EmptyFileSize": "0 bytes",
    "FilePickerHeader": "Filvelger",
    "FileSizeField": "Filstørrelse",
    "FolderAltText": "Mappe",
    "FolderBackPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    "FolderFrontPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    "FolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    "FolderLabelTemplate": "{0}, Mappe, Endret {1}, redigert av {2}, {3} elementer, Privat",
    "FromLinkLinkLabel": "Fra en kobling",
    "ImageAltText": ". {0} Bilde",
    "ImageAriaLabelTemplate": ". {0} Bilde",
    "ImageLayoutPlaceholderText": "Oppsett",
    "ImageSizePlaceholderText": "Bildestørrelse",
    "ItemChildCountField": "Antall underordnede elementer",
    "LayoutOptionAll": "Alt",
    "LayoutOptionSquare": "Kvadratisk",
    "LayoutOptionTall": "Høy",
    "LayoutOptionWide": "Vid",
    "LearnMoreLink": "Få mer informasjon.",
    "LicenseOptionAll": "Alt",
    "LicenseOptionAny": "Bare Creative Commons",
    "LicensePlaceholderText": "Lisens",
    "LinkFileInstructions": "Lime inn en kobling til en fil i OneDrive for Business eller SharePoint Online",
    "ExternalLinkFileInstructions": "Lim inn en kobling til et nettsted, side, dokument, liste, bibliotek (https:// eller http://)",
    "LinkHeader": "Fra en kobling",
    "LinkImageInstructions": "Lime inn en kobling til et bilde i OneDrive for Business eller SharePoint Online",
    "ListLayoutAriaLabel": "Vis alternativer. {0}  {1} .",
    "ListLayoutCompact": "Kompakt visning",
    "ListLayoutCompactDescription": "Vise elementer og detaljer i en kompakt liste",
    "ListLayoutList": "Listevisning",
    "ListLayoutListDescrition": "Vise elementer og detaljer i en liste",
    "ListLayoutTile": "Side ved side-visning",
    "ListLayoutTileDescription": "Vise elementer med forhåndsvisninger av fliser",
    "ListOptionsAlt": "Vis alternativer. {0} valgt .",
    "ListOptionsTitle": "Åpne menyen for visningsalternativer",
    "Loading": "Lasting...",
    "ModifiedByField": "Endret av",
    "ModifiedField": "Dato endret",
    "NameField": "Navn",
    "No": "Nei",
    "ProvidedValueIsInvalid": "Forutsatt at verdien er ugyldig",
    "NoExternalLinksValidationMessage": "Vi støtter bare kobling til filer i din egen organisasjon.",
    "NoImageValidationMessage": "Dette er ikke en kobling til en filtype vi støtter. Du kan bare koble til et bilde.",
    "NoRecentFiles": "Ingen nylig brukte filer",
    "NoRecentFilesDescription": "Prøv å velge en fil fra nettstedet ditt, eller last opp en fra enheten din.",
    "NoResultsBadEnglish": "Det er ikke funnet noe resultat. Prøv å endre filteralternativene",
    "ODModifiedField": "Modifisert",
    "ODPhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    "ODRowArialLabelTemplate": "{0}, {1}, Modifisert {2}, redigert av {3}, {4}, {5}",
    "OneDriveConfirmDialogBody": "Dette elementet er fra OneDrive-nettstedet ditt. Filer og mapper i OneDrive er private med mindre du deler dem. Har du delt denne filen med nettstedets medlemmer slik at de får tilgang til den?",
    "OneDriveConfirmDialogTitle": "Bare å sjekke ...",
    "OneDriveEmptyFolderAlt": "Tom mappe",
    "OneDriveEmptyFolderDescription": "Hvis du vil legge til filer, går du til OneDrive. Du kan også legge til filer i denne mappen ved hjelp av OneDrive-appen for datamaskinen.",
    "OneDriveEmptyFolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    "OneDriveEmptyFolderTitle": "Denne mappen er tom",
    "OneDriveRootFolderName": "Filer",
    "OpenButtonLabel": "Åpen",
    "PhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    "OrgAssetsTabLabel": "Bilder og filer levert av organisasjonen",
    "PoweredByBing": "Drevet av Bing",
    "RecentDocumentsHeader": "Nylig brukte dokumenter",
    "RecentImagesHeader": "Nylige bilder",
    "RecentLinkLabel": "Fersk",
    "SearchBoxPlaceholder": "Nettsøk",
    "SearchResultAlt": "Bilderesultat for {0}.",
    "SearchResultAriaLabel": "Trykk enter for å åpne bildekilden i en ny fane.",
    "Selected": "utvalgt",
    "SharingField": "Deler",
    "SharingPrivate": "Privat",
    "SharingShared": "Delte",
    "SiteLinkLabel": "Tomt",
    "SizeOptionAll": "Alt",
    "SizeOptionExtraLarge": "Ekstra stor",
    "SizeOptionLarge": "Stor",
    "SizeOptionMedium": "Middels",
    "SizeOptionSmall": "Liten",
    "SizeUnit": [
      "Byte",
      "KB",
      "MB",
      "GB",
      "TB",
      "PB",
      "HUND",
      "F.EKS",
      "YB"
    ],
    "SorryWebSearch": "Beklager, denne funksjonen er ikke implementert i dette eksemplet, fordi det ville kreve en Bing API-nøkkel.",
    "SortedAscending": "Sortert A til Å",
    "SortedDescending": "Sortert Å til A",
    "TypeAriaLabel": "Kolonneoperasjoner for Filtype, trykk for å sortere etter filtype",
    "UploadFileHeader": "Last opp fil",
    "UploadImageHeader": "Last opp bilde",
    "UploadLinkLabel": "Opplasting",
    "WebSearchLinkLabel": "Nettsøk",
    "Yes": "Ja",
    "StockImagesLinkLabel": "Arkivbilder",
    "StockImagesHeader": "Stock Bilder",
    "DateTime": {
      "L_RelativeDateTime_AFewSecondsFuture": "Om noen sekunder",
      "L_RelativeDateTime_AFewSeconds": "For noen sekunder siden",
      "L_RelativeDateTime_AboutAMinuteFuture": "På omtrent et minutt",
      "L_RelativeDateTime_AboutAMinute": "Omtrent et minutt siden",
      "L_RelativeDateTime_XMinutesFuture": "Om {0} minutt || På {0} minutter",
      "L_RelativeDateTime_XMinutes": "{0} minutt siden || {0} minutter siden",
      "L_RelativeDateTime_XMinutesFutureIntervals": "1|| 2-",
      "L_RelativeDateTime_XMinutesIntervals": "1|| 2-",
      "L_RelativeDateTime_AboutAnHourFuture": "På omtrent en time",
      "L_RelativeDateTime_AboutAnHour": "For omtrent en time siden",
      "L_RelativeDateTime_Tomorrow": "I morgen",
      "L_RelativeDateTime_Yesterday": "I går",
      "L_RelativeDateTime_TomorrowAndTime": "I morgen kl {0}",
      "L_RelativeDateTime_YesterdayAndTime": "I går på {0}",
      "L_RelativeDateTime_XHoursFuture": "Om {0} time|| Om {0} timer",
      "L_RelativeDateTime_XHours": "{0} time siden || {0} timer siden",
      "L_RelativeDateTime_XHoursFutureIntervals": "1|| 2-",
      "L_RelativeDateTime_XHoursIntervals": "1|| 2-",
      "L_RelativeDateTime_DayAndTime": "{0} på {1}",
      "L_RelativeDateTime_XDaysFuture": "{0} dag fra nå || {0} dager fra nå",
      "L_RelativeDateTime_XDays": "{0} dag siden || {0} dager siden",
      "L_RelativeDateTime_XDaysFutureIntervals": "1|| 2-",
      "L_RelativeDateTime_XDaysIntervals": "1|| 2-",
      "L_RelativeDateTime_Today": "I dag"
    },
    "NewFolderNamePlaceholder": "Skriv inn mappenavnet ditt",
    "FolderFilterBoxPlaceholder": "Filtrere mapper etter navn",
    "FolderExplorerLoading": "Laster inn mapper ...",
    "FolderExplorerNoItems": "Denne mappen har ingen undermapper.",
    "IncorrectGuidValidationMessage": "Angi en gyldig GUID",
    "SelectedLabel": "Utvalgt",
    "SelectIcon": "Velg ikon",
    "CloseButton": "Lukke",
    "MonacoEditorOpenButtonLabel": "Åpne redigeringsprogram",
    "MonacoEditorCancelButtonLabel": "Annullere",
    "MonacoEditorSaveButtonLabel": "Lagre",
    "MonacoEditorPanelTitle": "Rediger mal",
    "ColorPickerStrings": {
      "rootAriaLabelFormat": "{0} avdelinger velges.",
      "hex": "6e utg.",
      "red": "rød",
      "green": "grønn",
      "blue": "Hvordan fylle ut",
      "alpha": "Alfa",
      "transparency": "Caurredzamība",
      "alphaAriaLabel": "Alfa",
      "transparencyAriaLabel": "Caurredzamība",
      "hueAriaLabel": "Ljoegovas",
      "svAriaLabel": "Metning og lysstyrke",
      "svAriaValueFormat": "{1} metning {0} lysstyrke",
      "svAriaDescription": "Bruk venstre og høyre pil for å justere metningen. For å justere lysstyrken, bruk opp- og nedpilene.",
      "hexError": "sekskantede verdier må være mellom 3 og 6 tegn",
      "alphaError": "alfa skal være fra 0 til 100",
      "transparencyError": "Lysbilder må være fra 0 til 100",
      "redError": "Rød skal være fra 0 til 255",
      "greenError": "Grønn skal være fra 0 til 255",
      "blueError": "Blå skal være fra 0 til 255"
    }
  };
});