define([], function() {
  return {
    ApplyButtonLabel: "Anvende",
    ImportButtonLabel: "Importere",
    ExportButtonLabel: "Eksportere",
    JsonFileRequiredMessage: "Vennligst last opp en json fil",
    SaveButtonLabel: "Lagre",
    CancelButtonLabel: "Avbryt",
    PeoplePickerSuggestedContacts: "Foreslåtte personer",
    PeoplePickerSuggestedGroups: "Foreslåtte grupper",
    PeoplePickerSuggestedCombined: "Foreslåtte personer og grupper",
    PeoplePickerNoResults: "Ingen result funnet",
    PeoplePickerLoading: "Laster resultater ...",
    DatePickerMonthLongJanuary: "Januar",
    DatePickerMonthShortJanuary: "Jan",
    DatePickerMonthLongFebruary: "Februar",
    DatePickerMonthShortFebruary: "Feb",
    DatePickerMonthLongMarch: "Mars",
    DatePickerMonthShortMarch: "Mar",
    DatePickerMonthLongApril: "April",
    DatePickerMonthShortApril: "Apr",
    DatePickerMonthLongMay: "Mai",
    DatePickerMonthShortMay: "Mai",
    DatePickerMonthLongJune: "Juni",
    DatePickerMonthShortJune: "Jun",
    DatePickerMonthLongJuly: "Juli",
    DatePickerMonthShortJuly: "Jul",
    DatePickerMonthLongAugust: "August",
    DatePickerMonthShortAugust: "Aug",
    DatePickerMonthLongSeptember: "September",
    DatePickerMonthShortSeptember: "Sep",
    DatePickerMonthLongOctober: "Oktober",
    DatePickerMonthShortOctober: "Okt",
    DatePickerMonthLongNovember: "November",
    DatePickerMonthShortNovember: "Nov",
    DatePickerMonthLongDecember: "Desember",
    DatePickerMonthShortDecember: "Des",
    DatePickerDayLongSunday: "Søndag",
    DatePickerDayShortSunday: "Søn",
    DatePickerDayLongMonday: "Mandag",
    DatePickerDayShortMonday: "Man",
    DatePickerDayLongTuesday: "Tirsdag",
    DatePickerDayShortTuesday: "Tir",
    DatePickerDayLongWednesday: "Onsdag",
    DatePickerDayShortWednesday: "Ons",
    DatePickerDayLongThursday: "Torsdag",
    DatePickerDayShortThursday: "Tor",
    DatePickerDayLongFriday: "Fredag",
    DatePickerDayShortFriday: "Fre",
    DatePickerDayLongSaturday: "Lørdag",
    DatePickerDayShortSaturday: "Lør",
    DatepickerGoToToday: "I dag",
    DateTimePickerDate: "Dato",
    DateTimePickerTime: "Tid",
    ColorPickerButtonTitle: "Velg en farge",
    NotNumberValidationMessage: "Verdien skal være et nummer, men er:",
    MinimumNumberValidationMessage: "Verdien skal være større enn:",
    MaximumNumberValidationMessage: "Verdien skal være mindre enn:",
    TermPickerNoTerms: "Term settet inneholder ingen termer",
    TermPickerExpandTitle: "Utvid dette termsettet",
    TermPickerExpandNode: "Ekspander denne noden",
    TermPickerMenuTermSet: "Meny for Termsettet",
    TermPickerMenuGroup: "Meny for Termsettet",
    TermPickerInLabel: "inn",
    TermPickerTermSetLabel: "Termset",
    propertyFieldMultiSelectNoOptions: "Ingen alternativer å velge",
    CollectionDataEmptyFields: "Ingen felt ble angitt for samlingen av data.",
    CollectionDataEmptyValue: "Ingen data i samlingen din.",
    CollectionAddRowButtonLabel: "Legg data i samlingen",
    CollectionDeleteRowButtonLabel: "Slett den gjeldene raden",
    CollectionSaveAndAddButtonLabel: "Legg til og lagre",
    CollectionDataItemShowErrorsLabel: "Vis radfeil",
    CollectionDataItemFieldRequiredLabel: "Feltet er påkrevet.",
    InvalidUrlError: "Den angitte nettadressen er ikke gyldig",
    DescriptionLabel: "Beskrivelse",
    MoreInfoLabel: "Mer informasjon",
    AboutGroupLabel: "Om",

  AddFileButtonLabel: "Legg til fil",
  AddImageButtonLabel: "Legg til bilde",
  AriaCellValue: "{0} kolonne {1}",
  FilePickerCancelButtonLabel: "Avbryte",
  CantValidateValidationMessage: "Vi kunne ikke bekrefte denne koblingen. Kontroller koblingen, og prøv på nytt.",
  ChangeFileLinkLabel: "Endre fil",
  ChangeImageLinkLabel: "Endre bilde",
  ChooseFileLinkLabel: "Velg fil",
  ChooseImageLinkLabel: "Velg bilde",
  CopyrightUrl: "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
  CopyrightWarning: "Du er ansvarlig for å respektere andres rettigheter, inkludert opphavsrett.",
  CreativeCommonsMessage: "Disse resultatene er merket med Creative Commons-lisenser. Se gjennom lisensene for å sikre at du overholder dem.",
  DateFormat: "MM/DD/åååå hh: mm A",
  DocumentLabelTemplate: "{0}, dokument, endret {1}, redigert av {2}, privat",
  DocumentLibraries: "Dokumentbiblioteker",
  EditedByNamePlate: "redigert av ",
  EmptyFileSize: "0 byte",
  FilePickerHeader: "Fil velger",
  FileSizeField: "Filstørrelse",
  FolderAltText: "Mappen",
  FolderBackPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
  FolderFrontPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
  FolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
  FolderLabelTemplate: "{0}, mappe, endret {1}, redigert av {2}, {3} elementer, privat",
  FromLinkLinkLabel: "Fra en kobling",
  ImageAltText: ". {0} bilde",
  ImageAriaLabelTemplate: ". {0} bilde",
  ImageLayoutPlaceholderText: "Oppsett",
  ImageSizePlaceholderText: "Bildestørrelse",
  ItemChildCountField: "Antall underordnede elementer",
  LayoutOptionAll: "Alle",
  LayoutOptionSquare: "Square",
  LayoutOptionTall: "Høye",
  LayoutOptionWide: "Bredt",
  LearnMoreLink: "få mer informasjon.",
  LicenseOptionAll: "Alle",
  LicenseOptionAny: "Creative Commons bare",
  LicensePlaceholderText: "Lisens",
  LinkFileInstructions: "Lime inn en kobling til en fil i OneDrive for Business eller SharePoint Online",
  LinkHeader: "Fra en kobling",
  LinkImageInstructions: "Lime inn en kobling til et bilde i OneDrive for Business eller SharePoint Online",
  ListLayoutAriaLabel: "Vis alternativer. {0} {1}.",
  ListLayoutCompact: "Kompakt visning",
  ListLayoutCompactDescription: "Vise elementer og detaljer i en kompakt liste",
  ListLayoutList: "Listevisning",
  ListLayoutListDescrition: "Vise elementer og detaljer i en liste",
  ListLayoutTile: "Flislagt utsikt",
  ListLayoutTileDescription: "Vise elementer med forhåndsvisninger av fliser",
  ListOptionsAlt: "Vis alternativer. {0} valgt.",
  ListOptionsTitle: "Åpne menyen for visningsalternativer",
  Loading: "Lasting...",
  ModifiedByField: "Endret av",
  ModifiedField: "Endret dato",
  NameField: "navn",
  No: "nei",
  ProvidedValueIsInvalid: "Angitt verdi er ugyldig",
  NoExternalLinksValidationMessage: "Vi støtter bare kobling til filer i din egen organisasjon.",
  NoImageValidationMessage: "Dette er ikke en kobling til en filtype vi støtter. Du kan bare koble til et bilde.",
  NoRecentFiles: "Ingen nylige filer",
  NoRecentFilesDescription: "Prøv å velge en fil fra nettstedet ditt, eller Last opp en fra enheten din.",
  NoResultsBadEnglish: "Det finnes ingen resultater. Prøv å endre filteralternativene",
  ODModifiedField: "Endret",
  ODPhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
  ODRowArialLabelTemplate: "{0}, {1}, modifisert {2}, redigert av {3}, {4}, {5}",
  OneDriveConfirmDialogBody: "Dette elementet er fra OneDrive-webområdet. Filer og mapper i OneDrive er private med mindre du deler dem. Har du delt denne filen med område medlemmene slik at de kan tilgangen den?",
  OneDriveConfirmDialogTitle: "Bare sjekker...",
  OneDriveEmptyFolderAlt: "Tøm mappe",
  OneDriveEmptyFolderDescription: "Hvis du vil legge til filer, går du til OneDrive. Du kan også legge til filer i denne mappen ved hjelp av OneDrive-appen for datamaskinen.",
  OneDriveEmptyFolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
  OneDriveEmptyFolderTitle: "Denne mappen er tom",
  OneDriveRootFolderName: "Filer",
  OpenButtonLabel: "Åpne",
  PhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
  OrgAssetsTabLabel: "Bilder og filer fra organisasjonen",
  PoweredByBing: "Drevet av Bing",
  RecentDocumentsHeader: "Nylig brukte dokumenter",
  RecentImagesHeader: "Nylige bilder",
  RecentLinkLabel: "Siste",
  SearchBoxPlaceholder: "Søk på weben",
  SearchResultAlt: "Bilde resultatet for {0}.",
  SearchResultAriaLabel: "Trykk på Enter for å åpne bildekilden i en ny fane.",
  Selected: "Valgte",
  SharingField: "Deler",
  SharingPrivate: "Privat",
  SharingShared: "Delte",
  SiteLinkLabel: "Nettstedet",
  SizeOptionAll: "Alle",
  SizeOptionExtraLarge: "Ekstra stor",
  SizeOptionLarge: "Store",
  SizeOptionMedium: "Medium",
  SizeOptionSmall: "Liten",
  SizeUnit: [
    "Byte",
    "Kb",
    "Mb",
    "Gb",
    "Tb",
    "Pb",
    "Eb",
    "F.eks",
    "Yb"
  ],
  SorryWebSearch: "Beklager, denne funksjonen er ikke implementert i dette eksemplet, fordi det ville kreve en Bing API-nøkkel.",
  SortedAscending: "Sortert A til å",
  SortedDescending: "Sortert Z til A",
  TypeAriaLabel: "Kol onne operasjoner for filtype Trykk for å sortere etter filtype",
  UploadFileHeader: "Last opp fil",
  UploadImageHeader: "Last opp bilde",
  UploadLinkLabel: "Laste opp",
  WebSearchLinkLabel: "Søk på weben",
  Yes: "ja",
  
  DateTime: {
      "L_RelativeDateTime_AFewSecondsFuture": "Om noen få sekunder",
      "L_RelativeDateTime_AFewSeconds": "Et par sekunder siden",
      "L_RelativeDateTime_AboutAMinuteFuture": "I omtrent et minutt",
      "L_RelativeDateTime_AboutAMinute": "Om et minutt siden",
      "L_RelativeDateTime_XMinutesFuture": "I {0} minutt||På {0} minutter",
      "L_RelativeDateTime_XMinutes": "{0} minutt siden||{0} minutter siden",
      "L_RelativeDateTime_XMinutesFutureIntervals": "1||2-",
      "L_RelativeDateTime_XMinutesIntervals": "1||2-",
      "L_RelativeDateTime_AboutAnHourFuture": "Om en time",
      "L_RelativeDateTime_AboutAnHour": "For en time siden",
      "L_RelativeDateTime_Tomorrow": "Morgen",
      "L_RelativeDateTime_Yesterday": "Går",
      "L_RelativeDateTime_TomorrowAndTime": "I morgen kl {0}",
      "L_RelativeDateTime_YesterdayAndTime": "I går på {0}",
      "L_RelativeDateTime_XHoursFuture": "I {0} time||I {0} timer",
      "L_RelativeDateTime_XHours": "{0} time siden||{0} timer siden",
      "L_RelativeDateTime_XHoursFutureIntervals": "1||2-",
      "L_RelativeDateTime_XHoursIntervals": "1||2-",
      "L_RelativeDateTime_DayAndTime": "{0} {1}",
      "L_RelativeDateTime_XDaysFuture": "{0} dag fra nå||{0} dager fra nå",
      "L_RelativeDateTime_XDays": "{0} dag siden||{0} dager siden",
      "L_RelativeDateTime_XDaysFutureIntervals": "1||2-",
      "L_RelativeDateTime_XDaysIntervals": "1||2-",
      "L_RelativeDateTime_Today": "Dag"
    },
  }
});