define([], function() {
    return {
      ApplyButtonLabel: "Применить",
      ImportButtonLabel: "Импорт",
      ExportButtonLabel: "Экспорт",
      JsonFileRequiredMessage: "Пожалуйста, добавьте файл json",
      SaveButtonLabel: "Сохранить",
      CancelButtonLabel: "Отмена",
      PeoplePickerSuggestedContacts: "Предложенные пользователи",
      PeoplePickerSuggestedGroups: "Предложенные группы",
      PeoplePickerSuggestedCombined: "Предложенные пользователи и группы",
      PeoplePickerNoResults: "Нет результатов, удовлетворяющих условиям",
      PeoplePickerLoading: "Загрузка результатов...",
      DatePickerMonthLongJanuary: "Январь",
      DatePickerMonthShortJanuary: "Янв",
      DatePickerMonthLongFebruary: "Февраль",
      DatePickerMonthShortFebruary: "Фев",
      DatePickerMonthLongMarch: "Март",
      DatePickerMonthShortMarch: "Мар",
      DatePickerMonthLongApril: "Апрель",
      DatePickerMonthShortApril: "Апр",
      DatePickerMonthLongMay: "Май",
      DatePickerMonthShortMay: "Май",
      DatePickerMonthLongJune: "Июнь",
      DatePickerMonthShortJune: "Июн",
      DatePickerMonthLongJuly: "Июль",
      DatePickerMonthShortJuly: "Июл",
      DatePickerMonthLongAugust: "Август",
      DatePickerMonthShortAugust: "Авг",
      DatePickerMonthLongSeptember: "Сентябрь",
      DatePickerMonthShortSeptember: "Сен",
      DatePickerMonthLongOctober: "Октябрь",
      DatePickerMonthShortOctober: "Окт",
      DatePickerMonthLongNovember: "Ноябрь",
      DatePickerMonthShortNovember: "Ноя",
      DatePickerMonthLongDecember: "Декабрь",
      DatePickerMonthShortDecember: "Дек",
      DatePickerDayLongSunday: "Воскресенье",
      DatePickerDayShortSunday: "Вс",
      DatePickerDayLongMonday: "Понедельник",
      DatePickerDayShortMonday: "Пн",
      DatePickerDayLongTuesday: "Вторник",
      DatePickerDayShortTuesday: "Вт",
      DatePickerDayLongWednesday: "Среда",
      DatePickerDayShortWednesday: "Ср",
      DatePickerDayLongThursday: "Четверг",
      DatePickerDayShortThursday: "Чт",
      DatePickerDayLongFriday: "Пятница",
      DatePickerDayShortFriday: "Пт",
      DatePickerDayLongSaturday: "Суббота",
      DatePickerDayShortSaturday: "Сб",
      DatepickerGoToToday: "Сегодня",
      DateTimePickerDate: "Дата",
      DateTimePickerTime: "Время",
      ColorPickerButtonTitle: "Выберите цвет",
      NotNumberValidationMessage: "Значение должно быть числом, текущее значение:",
      MinimumNumberValidationMessage: "Значение должно быть больше, чем:",
      MaximumNumberValidationMessage: "Значение должно быть меньше, чем:",
      TermPickerNoTerms: "Данный набор терминов пуст",
      TermPickerExpandTitle: "Развернуть этот набор терминов",
      TermPickerExpandNode: "Развернуть этот узел",
      TermPickerMenuTermSet: "Меню для набора терминов",
      TermPickerMenuGroup: "Меню для группы терминов",
      TermPickerInLabel: "в",
      TermPickerTermSetLabel: "Набор терминов",
      propertyFieldMultiSelectNoOptions: "Нет элементов для выбора",
      CollectionDataEmptyFields: "Набор данных не содержит полей.",
      CollectionDataEmptyValue: "Набор данных пуст.",
      CollectionAddRowButtonLabel: "Добавить данные в набор",
      CollectionDeleteRowButtonLabel: "Удалить данную строку",
      CollectionSaveAndAddButtonLabel: "Добавить и сохранить",
      CollectionDataItemShowErrorsLabel: "Отобразить ошибки для строки",
      CollectionDataItemFieldRequiredLabel: "Это поле не может быть пустым.",
      InvalidUrlError: "Заданное значение не является корректной ссылкой",
      DescriptionLabel: "Описание",
      MoreInfoLabel: "Подробнее",
      AboutGroupLabel: "Справка",

      AddFileButtonLabel: "Добавить файл",
      AddImageButtonLabel: "Добавить изображение",
      AriaCellValue: "{0} колонка, {1}",
      FilePickerCancelButtonLabel: "Отменить",
      CantValidateValidationMessage: "Мы не смогли проверить данную ссылку. Пожалуйста, проверьте ссылку и попробуйте еще раз.",
      ChangeFileLinkLabel: "Изменить файл",
      ChangeImageLinkLabel: "Изменить изображение",
      ChooseFileLinkLabel: "Выбрать файл",
      ChooseImageLinkLabel: "Выбрать изображение",
      CopyrightUrl: "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
      CopyrightWarning: "Вы ответственны за соблюдение чужих прав, включая авторские права.",
      CreativeCommonsMessage: "Данные результаты помечены лицензией Creative Commons. Ознакомьтесь с лицензией, чтобы убедиться в ее соблюдении.",
      DateFormat: "DD/MM/YYYY hh:mm",
      DocumentLabelTemplate: "{0}, Документ, Дата изменения {1}, Изменен {2}, Частный",
      DocumentLibraries: "Библиотеки документов",
      EditedByNamePlate: "Изменен ",
      EmptyFileSize: "0 байтов",
      FilePickerHeader: "Выбор файла",
      FileSizeField: "Размер файла",
      FolderAltText: "Папка",
      FolderBackPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
      FolderFrontPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
      FolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
      FolderLabelTemplate: "{0}, Папка, Дата изменения {1}, Изменена {2}, {3} элементов, Частная",
      FromLinkLinkLabel: "По ссылке",
      ImageAltText: ".{0} Изображение",
      ImageAriaLabelTemplate: ".{0} Изображение",
      ImageLayoutPlaceholderText: "Макет",
      ImageSizePlaceholderText: "Размер изображения",
      ItemChildCountField: "Число дочерних элементов",
      LayoutOptionAll: "Все",
      LayoutOptionSquare: "Плитки",
      LayoutOptionTall: "Высокий",
      LayoutOptionWide: "Широкий",
      LearnMoreLink: "Узнать больше.",
      LicenseOptionAll: "Все",
      LicenseOptionAny: "Только Creative Commons",
      LicensePlaceholderText: "Лицензия",
      LinkFileInstructions: "Вставьте ссылку на файл в OneDrive для Бизнеса или SharePoint Online",
      LinkHeader: "По ссылке",
      LinkImageInstructions: "Вставьте ссылку на изображение в OneDrive для Бизнеса или SharePoint Online",
      ListLayoutAriaLabel: "Параметры просмотра. {0}  {1} .",
      ListLayoutCompact: "Сокращенный список",
      ListLayoutCompactDescription: "Просмотр элементов и сведений в виде сокращенного списка",
      ListLayoutList: "Список",
      ListLayoutListDescrition: "Просмотр элементов и сведений в виде списка",
      ListLayoutTile: "Плитки",
      ListLayoutTileDescription: "Показать плитки элементов",
      ListOptionsAlt: "Параметры просмотра. Выбрано {0}.",
      ListOptionsTitle: "Переключение параметров просмотра",
      Loading: "Загрузка...",
      ModifiedByField: "Кем измененено",
      ModifiedField: "Изменено",
      NameField: "Имя",
      No: "Нет",
      ProvidedValueIsInvalid: "Введено неверное значение",
      NoExternalLinksValidationMessage: "Мы поддерживаем добавление файлов по ссылке только из Вашей организации.",
      NoImageValidationMessage: "Мы не поддерживаем данный тип файла. Вы можете добавлять только изображения.",
      NoRecentFiles: "Ничего не найдено",
      NoRecentFilesDescription: "Попробуйте выбрать файл с вашего сайта или загрузить с жесткого диска.",
      NoResultsBadEnglish: "***Ничего не найдено. Попробуйте поменять параметры запроса",
      ODModifiedField: "Кем изменен",
      ODPhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
      ODRowArialLabelTemplate: "{0}, {1}, Дата изменения {2}, изменен {3}, {4}, {5}",
      OneDriveConfirmDialogBody: "Выбран элемент из OneDrive. Файлы из папки OneDrive находятся в частном доступе до тех пор, пока не Вы не поделитесь ими. Проверьте, что Вы поделились данным файлом с Вашими коллегами, чтобы они могли работать с ним.",
      OneDriveConfirmDialogTitle: "Проверяем...",
      OneDriveEmptyFolderAlt: "Папка пуста",
      OneDriveEmptyFolderDescription: "Откройте OneDrive, чтобы добавить файлы. Вы также можете добавить файлы в данную папку через приложение OneDrive на Вашем компьютере.",
      OneDriveEmptyFolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
      OneDriveEmptyFolderTitle: "Папка пуста",
      OneDriveRootFolderName: "Файлы",
      OpenButtonLabel: "Открыть",
      PhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
      OrgAssetsTabLabel: "Изображения и файлы из Вашей организации",
      PoweredByBing: "Работает на Bing",
      RecentDocumentsHeader: "Последние документы",
      RecentImagesHeader: "Последние изображения",
      RecentLinkLabel: "Последние",
      SearchBoxPlaceholder: "Поиск в Веб",
      SearchResultAlt: "Результат для {0}.",
      SearchResultAriaLabel: "Нажмите Ввод, чтобы открыть изображение в отдельной вкладке.",
      Selected: "выбран",
      SharingField: "Поделиться",
      SharingPrivate: "Частный",
      SharingShared: "Общией",
      SiteLinkLabel: "Сайт",
      SizeOptionAll: "Все",
      SizeOptionExtraLarge: "Очень большой",
      SizeOptionLarge: "Большой",
      SizeOptionMedium: "Средний",
      SizeOptionSmall: "Маленький",
      SizeUnit: [
        "байт",
        "Кб",
        "Мб",
        "Гб",
        "Тб",
        "Пб",
        "Еб",
        "Зб",
        "Иб"
      ],
      SorryWebSearch: "Извините, данная функция не реализована в примере, так как требует ключа API для Bing",
      SortedAscending: "Отсортировано А - Я",
      SortedDescending: "Отсортировано Я - А",
      TypeAriaLabel: "Операции колонки Тип файла. Нажмите, чтобы отфильтровать по типу файла",
      UploadFileHeader: "Загрузить файл",
      UploadImageHeader: "Загрузить изображение",
      UploadLinkLabel: "Загрузить",
      WebSearchLinkLabel: "Поиск по Веб",
      Yes: "Да",

    DateTime: {
      "L_RelativeDateTime_AFewSecondsFuture": "Через несколько секунд",
      "L_RelativeDateTime_AFewSeconds": "Несколько секунд назад",
      "L_RelativeDateTime_AboutAMinuteFuture": "Примерно через минуту",
      "L_RelativeDateTime_AboutAMinute": "Примерно минуту назад",
      "L_RelativeDateTime_XMinutesFuture": "Через {0} мин",
      "L_RelativeDateTime_XMinutes": "{0} мин назад",
      "L_RelativeDateTime_XMinutesFutureIntervals": "1-",
      "L_RelativeDateTime_XMinutesIntervals": "1-",
      "L_RelativeDateTime_AboutAnHourFuture": "Примерно через час",
      "L_RelativeDateTime_AboutAnHour": "Примерно час назад",
      "L_RelativeDateTime_Tomorrow": "Завтра",
      "L_RelativeDateTime_Yesterday": "Вчера",
      "L_RelativeDateTime_TomorrowAndTime": "Завтра в {0}",
      "L_RelativeDateTime_YesterdayAndTime": "Вчера в {0}",
      "L_RelativeDateTime_XHoursFuture": "Через {0} ч",
      "L_RelativeDateTime_XHours": "{0} ч назад",
      "L_RelativeDateTime_XHoursFutureIntervals": "1-",
      "L_RelativeDateTime_XHoursIntervals": "1-",
      "L_RelativeDateTime_DayAndTime": "{0}, в {1}",
      "L_RelativeDateTime_XDaysFuture": "Через {0} день||Через {0} дн.",
      "L_RelativeDateTime_XDays": "{0} день назад||Дней назад: {0}",
      "L_RelativeDateTime_XDaysFutureIntervals": "1 евро 2-",
      "L_RelativeDateTime_XDaysIntervals": "1 евро 2-",
      "L_RelativeDateTime_Today": "Сегодня"
    }
    
    }
  });
  