define([], () => {
  return {
    "ApplyButtonLabel": "Tillämpa",
    "ImportButtonLabel": "Importera",
    "ExportButtonLabel": "Exportera",
    "FormatCodeButtonLabel": "Formatera kod",
    "JsonFileRequiredMessage": "Vänligen ladda upp en json-fil",
    "EditPropertiesButtonLabel": "Redigera egenskaper",
    "EditPropertiesPanelHeaderText": "Redigera råegenskaper",
    "SaveButtonLabel": "Spara",
    "CancelButtonLabel": "Avbryt",
    "PeoplePickerSuggestedContacts": "Förslag på personer",
    "PeoplePickerSuggestedGroups": "Föreslagna grupper",
    "PeoplePickerSuggestedCombined": "Förslag på personer och grupper",
    "PeoplePickerNoResults": "Inget resultat hittades",
    "PeoplePickerLoading": "Laddar resultat ...",
    "DatePickerMonthLongJanuary": "Januari",
    "DatePickerMonthShortJanuary": "Jan",
    "DatePickerMonthLongFebruary": "Februari",
    "DatePickerMonthShortFebruary": "Feb",
    "DatePickerMonthLongMarch": "Mars",
    "DatePickerMonthShortMarch": "Mar",
    "DatePickerMonthLongApril": "April",
    "DatePickerMonthShortApril": "Apr",
    "DatePickerMonthLongMay": "Maj",
    "DatePickerMonthShortMay": "Maj",
    "DatePickerMonthLongJune": "Juni",
    "DatePickerMonthShortJune": "Jun",
    "DatePickerMonthLongJuly": "Juli",
    "DatePickerMonthShortJuly": "Jul",
    "DatePickerMonthLongAugust": "Augusti",
    "DatePickerMonthShortAugust": "Aug",
    "DatePickerMonthLongSeptember": "September",
    "DatePickerMonthShortSeptember": "Sep",
    "DatePickerMonthLongOctober": "Oktober",
    "DatePickerMonthShortOctober": "Okt",
    "DatePickerMonthLongNovember": "November",
    "DatePickerMonthShortNovember": "Nov",
    "DatePickerMonthLongDecember": "December",
    "DatePickerMonthShortDecember": "Dec",
    "DatePickerDayLongSunday": "Söndag",
    "DatePickerDayShortSunday": "Sön",
    "DatePickerDayLongMonday": "Måndag",
    "DatePickerDayShortMonday": "Mån",
    "DatePickerDayLongTuesday": "Tisdag",
    "DatePickerDayShortTuesday": "Tis",
    "DatePickerDayLongWednesday": "Onsdag",
    "DatePickerDayShortWednesday": "Ons",
    "DatePickerDayLongThursday": "Torsdag",
    "DatePickerDayShortThursday": "Tors",
    "DatePickerDayLongFriday": "Fredag",
    "DatePickerDayShortFriday": "Fre",
    "DatePickerDayLongSaturday": "Lördag",
    "DatePickerDayShortSaturday": "Lör",
    "DatepickerGoToToday": "Idag",
    "DateTimePickerDate": "Datum",
    "DateTimePickerTime": "Tid",
    "ColorPickerButtonTitle": "Välj en färg",
    "NotNumberValidationMessage": "Värdet måste vara ett tal, faktiskt är:",
    "MinimumNumberValidationMessage": "Värdet måste vara större än eller lika med:",
    "MaximumNumberValidationMessage": "Värdet måste vara lägre än eller lika med:",
    "TermPickerNoTerms": "Termuppsättning innehåller inga villkor",
    "TermPickerExpandTitle": "Expandera den här termuppsättningen",
    "TermPickerExpandNode": "Expandera denna Nod",
    "TermPickerMenuTermSet": "Meny för termuppsättning",
    "TermPickerMenuTerm": "Meny för termin",
    "TermPickerMenuGroup": "Meny för Term Group",
    "TermPickerInLabel": "I",
    "TermPickerTermSetLabel": "Termuppsättning",
    "propertyFieldMultiSelectNoOptions": "Inga alternativ att välja",
    "CollectionDataEmptyFields": "Inga fält lämnades för insamlingsdata.",
    "CollectionDataEmptyValue": "Inga data i din samling.",
    "CollectionAddRowButtonLabel": "Lägga till data i samlingen",
    "CollectionDeleteRowButtonLabel": "Ta bort den aktuella raden",
    "CollectionSaveAndAddButtonLabel": "Lägg till och spara",
    "CollectionDataItemShowErrorsLabel": "Visa radfel",
    "CollectionDataItemFieldRequiredLabel": "Fält är obligatoriskt.",
    "CollectionDataItemFieldIssuesLabel": "Fältproblem:",
    "InvalidUrlError": "Den medföljande webbadressen är inte giltig",
    "DescriptionLabel": "Beskrivning",
    "MoreInfoLabel": "Mer info",
    "AboutGroupLabel": "Om",
    "SitePickerSearchBoxPlaceholder": "Sök...",
    "SitePickerNoResults": "Inga sökresultat",
    "SitePickerSitesChosen": "Webbplats(er) vald",
    "TeamPickerSearchBoxPlaceholder": "Sök...",
    "TeamPickerNoResults": "Inga sökresultat",
    "TeamPickerSitesChosen": "Lag(er) utvalda",
    "AddFileButtonLabel": "Lägg till fil",
    "AddImageButtonLabel": "Lägg till bild",
    "AriaCellValue": "{0} kolumn, {1}",
    "FilePickerCancelButtonLabel": "Avbryt",
    "CantValidateValidationMessage": "Vi kunde inte verifiera den här länken. Vänligen kontrollera länken och försök igen.",
    "ChangeFileLinkLabel": "Ändra fil",
    "ChangeImageLinkLabel": "Ändra bild",
    "ChooseFileLinkLabel": "Välj fil",
    "ChooseImageLinkLabel": "Välj bild",
    "CopyrightUrl": "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
    "CopyrightWarning": "Du ansvarar för att andras rättigheter respekteras, inklusive upphovsrätt.",
    "CreativeCommonsMessage": "Dessa resultat är märkta med Creative Commons-licenser. Granska licenserna för att säkerställa att du följer reglerna.",
    "DateFormat": "MM/DD/ÅÅÅÅ hh:mm A",
    "DeleteSelectedFileButtonLabel": "Ta bort vald fil",
    "DocumentLabelTemplate": "{0}, Dokument, Ändrad {1}, redigerad av {2}, Privat",
    "DocumentLibraries": "Dokumentbibliotek",
    "EditedByNamePlate": "redigerad av ",
    "EmptyFileSize": "0 byte",
    "FilePickerHeader": "Filväljare",
    "FileSizeField": "Filstorlek",
    "FolderAltText": "Mappen",
    "FolderBackPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    "FolderFrontPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    "FolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    "FolderLabelTemplate": "{0}, Mapp, Ändrad {1}, redigerad av {2}, {3} objekt, Privat",
    "FromLinkLinkLabel": "Från en länk",
    "ImageAltText": ". {0} Bild",
    "ImageAriaLabelTemplate": ". {0} Bild",
    "ImageLayoutPlaceholderText": "Layout",
    "ImageSizePlaceholderText": "Bildstorlek",
    "ItemChildCountField": "Antal underordnade objekt",
    "LayoutOptionAll": "Alla",
    "LayoutOptionSquare": "Kvadrat",
    "LayoutOptionTall": "Lång",
    "LayoutOptionWide": "Brett",
    "LearnMoreLink": "Läs mer.",
    "LicenseOptionAll": "Alla",
    "LicenseOptionAny": "Endast Creative Commons",
    "LicensePlaceholderText": "Licens",
    "LinkFileInstructions": "Klistra in en länk till en fil i OneDrive för företag eller SharePoint Online",
    "ExternalLinkFileInstructions": "Klistra in en länk till en webbplats, sida, dokument, lista, bibliotek (https:// eller http://)",
    "LinkHeader": "Från en länk",
    "LinkImageInstructions": "Klistra in en länk till en bild i OneDrive för företag eller SharePoint Online",
    "ListLayoutAriaLabel": "Visa alternativ. {0} {1} .",
    "ListLayoutCompact": "Kompakt vy",
    "ListLayoutCompactDescription": "Visa objekt och detaljer i en kompakt lista",
    "ListLayoutList": "Listvy",
    "ListLayoutListDescrition": "Visa objekt och detaljer i en lista",
    "ListLayoutTile": "Vyn Sida vid sida",
    "ListLayoutTileDescription": "Visa objekt med panelförhandsgranskningar",
    "ListOptionsAlt": "Visa alternativ. {0} markerad .",
    "ListOptionsTitle": "Öppna menyn visa alternativ",
    "Loading": "Laddar...",
    "ModifiedByField": "Ändrad av",
    "ModifiedField": "Datum ändrat",
    "NameField": "Namn",
    "No": "Nej",
    "ProvidedValueIsInvalid": "Förutsatt värde är ogiltigt",
    "NoExternalLinksValidationMessage": "Vi stöder endast länkning till filer i din egen organisation.",
    "NoImageValidationMessage": "Det här är ingen länk till en filtyp som vi stöder. Du kan bara länka till en bild.",
    "NoRecentFiles": "Inga senaste filer",
    "NoRecentFilesDescription": "Prova att välja en fil från webbplatsen, eller ladda upp en från enheten.",
    "NoResultsBadEnglish": "Inga resultat hittades. Försök att ändra filteralternativen",
    "ODModifiedField": "Ändrade",
    "ODPhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    "ODRowArialLabelTemplate": "{0}, {1}, Ändrad {2}, redigerad av {3}, {4}, {5}",
    "OneDriveConfirmDialogBody": "Det här objektet är från din OneDrive-webbplats. Filer och mappar på OneDrive är privata om du inte delar dem. Har du delat denna fil med dina webbplatsmedlemmar så att de kan komma åt dem?",
    "OneDriveConfirmDialogTitle": "Bara kolla...",
    "OneDriveEmptyFolderAlt": "Tom mapp",
    "OneDriveEmptyFolderDescription": "Om du vill lägga till filer går du till din OneDrive. Du kan också lägga till filer i den här mappen med hjälp av OneDrive-appen för datorn.",
    "OneDriveEmptyFolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    "OneDriveEmptyFolderTitle": "Den här mappen är tom",
    "OneDriveRootFolderName": "Filer",
    "OpenButtonLabel": "Öppna",
    "PhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    "OrgAssetsTabLabel": "Bilder och filer som tillhandahålls av din organisation",
    "PoweredByBing": "Drivs av Bing",
    "RecentDocumentsHeader": "Senaste dokumenten",
    "RecentImagesHeader": "Senaste bilder",
    "RecentLinkLabel": "Senaste",
    "SearchBoxPlaceholder": "Webbsökning",
    "SearchResultAlt": "Bildresultat för {0}.",
    "SearchResultAriaLabel": "Tryck på retur för att öppna bildkällan i en ny flik.",
    "Selected": "Markerade",
    "SharingField": "Dela",
    "SharingPrivate": "Privat",
    "SharingShared": "Delade",
    "SiteLinkLabel": "Webbplats",
    "SizeOptionAll": "Alla",
    "SizeOptionExtraLarge": "Extra Stor",
    "SizeOptionLarge": "Stora",
    "SizeOptionMedium": "Medium",
    "SizeOptionSmall": "Liten",
    "SizeUnit": [
      "Byte",
      "kB",
      "MB",
      "GB",
      "TB",
      "PB",
      "EB",
      "ZB",
      "YB"
    ],
    "SorryWebSearch": "Den här funktionen implementeras inte i det här exemplet eftersom den kräver en API-nyckel för Bing.",
    "SortedAscending": "Sorterat A till Ö",
    "SortedDescending": "Sorterad Ö till A",
    "TypeAriaLabel": "Kolumnåtgärder för Filtyp, Tryck för att sortera på Filtyp",
    "UploadFileHeader": "Ladda upp fil",
    "UploadImageHeader": "Ladda upp bild",
    "UploadLinkLabel": "Uppladdning",
    "WebSearchLinkLabel": "Webbsökning",
    "Yes": "Ja",
    "StockImagesLinkLabel": "Arkivbilder",
    "StockImagesHeader": "Stockbilder",
    "DateTime": {
      "L_RelativeDateTime_AFewSecondsFuture": "Om några sekunder",
      "L_RelativeDateTime_AFewSeconds": "För några sekunder sedan",
      "L_RelativeDateTime_AboutAMinuteFuture": "Om ungefär en minut",
      "L_RelativeDateTime_AboutAMinute": "För ungefär en minut sedan",
      "L_RelativeDateTime_XMinutesFuture": "Om {0} minut||Om {0} minuter",
      "L_RelativeDateTime_XMinutes": "För {0} minut sedan||För {0} minuter sedan",
      "L_RelativeDateTime_XMinutesFutureIntervals": "1||2-",
      "L_RelativeDateTime_XMinutesIntervals": "1||2-",
      "L_RelativeDateTime_AboutAnHourFuture": "Om ungefär en timme",
      "L_RelativeDateTime_AboutAnHour": "För ungefär en timme sedan",
      "L_RelativeDateTime_Tomorrow": "Imorgon",
      "L_RelativeDateTime_Yesterday": "Igår",
      "L_RelativeDateTime_TomorrowAndTime": "Imorgon vid {0}",
      "L_RelativeDateTime_YesterdayAndTime": "Igår vid {0}",
      "L_RelativeDateTime_XHoursFuture": "Om {0} timme||Om {0} timmar",
      "L_RelativeDateTime_XHours": "För {0} timme sedan||För {0} timmar sedan",
      "L_RelativeDateTime_XHoursFutureIntervals": "1||2-",
      "L_RelativeDateTime_XHoursIntervals": "1||2-",
      "L_RelativeDateTime_DayAndTime": "{0} på {1}",
      "L_RelativeDateTime_XDaysFuture": "Om {0} dag||Om {0} dagar",
      "L_RelativeDateTime_XDays": "För {0} dag sedan||För {0} dagar sedan",
      "L_RelativeDateTime_XDaysFutureIntervals": "1||2-",
      "L_RelativeDateTime_XDaysIntervals": "1||2-",
      "L_RelativeDateTime_Today": "Idag"
    },
    "NewFolderNamePlaceholder": "Ange ditt mappnamn",
    "FolderFilterBoxPlaceholder": "Filtrera mappar efter namn",
    "FolderExplorerLoading": "Läser in mappar...",
    "FolderExplorerNoItems": "Den här mappen har inga undermappar.",
    "IncorrectGuidValidationMessage": "Ange ett giltigt GUID",
    "SelectedLabel": "Vald",
    "SelectIcon": "Välj ikon",
    "CloseButton": "Stäng",
    "MonacoEditorOpenButtonLabel": "Öppna redigeraren",
    "MonacoEditorCancelButtonLabel": "Avbryt",
    "MonacoEditorSaveButtonLabel": "Spara",
    "MonacoEditorPanelTitle": "Redigera mall",
    "ColorPickerStrings": {
      "rootAriaLabelFormat": "Färgväljare, {0} vald.",
      "hex": "Hex",
      "red": "Röd",
      "green": "Grön",
      "blue": "Blå",
      "alpha": "Alfa",
      "transparency": "Transparens",
      "alphaAriaLabel": "Alfa",
      "transparencyAriaLabel": "Transparens",
      "hueAriaLabel": "Nyans",
      "svAriaLabel": "Mättnad och ljusstyrka",
      "svAriaValueFormat": "Ljusstyrka {1} {0} mättnad",
      "svAriaDescription": "Använd vänster- och högerpilarna för att justera mättnaden. Använd upp- och nedpilarna för att justera ljusstyrkan.",
      "hexError": "Hex-värden måste vara mellan 3 och 6 tecken långa",
      "alphaError": "Alfa måste vara mellan 0 och 100",
      "transparencyError": "Transparens måste vara mellan 0 och 100",
      "redError": "Rött måste vara mellan 0 och 255",
      "greenError": "Grönt måste vara mellan 0 och 255",
      "blueError": "Blått måste vara mellan 0 och 255"
    },
    "gridControlColumn1Label": "Titel",
    "gridControlColumn2Label": "Beskrivning",
  };
});